export type GuidanceLevel = "advanced" | "basics" | "extra";

export interface ExplainerBody {
  whatThisMeans: string;
  whyItMatters: string;
  healthyVsRisky: string;
  whatToDoNext: string;
}

export interface ExtraDepthContent {
  workedExample?: string;
  benchmarkDetail?: string;
  glossaryTerms?: string;
  financingInsight?: string;
}

export type ExplainerPriority = "high" | "standard";

export interface Explainer {
  id: string;
  title: string;
  body: ExplainerBody;
  extraBody?: ExtraDepthContent;
  audienceLevel: GuidanceLevel[];
  relatedSection: string;
  dismissible: boolean;
  autoExpandFor: GuidanceLevel[];
  order: number;
  highFriction: boolean;
  priority: ExplainerPriority;
}

export const EXPLAINERS: Record<string, Explainer> = {
  revenue: {
    id: "revenue",
    title: "Revenue",
    body: {
      whatThisMeans: "Revenue is all the money your school expects to bring in - tuition, public funding, grants, fundraising, and any other income sources. Think of it as the total fuel your school runs on.",
      whyItMatters: "Revenue follows enrollment - demand is the engine of your financial model. The strongest plans are anchored to dependable, enrollment-driven income (tuition, per-pupil funding) rather than uncertain sources like one-time grants. We see this distinction matter a lot in how models hold up over time.",
      healthyVsRisky: "A focused revenue model anchored to enrollment-driven income is a strength, not a weakness. The risk isn't having one dominant stream - it's relying on income that doesn't scale with student demand (like a single large grant). I'd look for revenue that grows reliably as enrollment grows.",
      whatToDoNext: "I'd start with your most certain, demand-driven revenue sources. If you're a tuition-based school, begin there. Add other sources only if you have reasonable confidence they'll come through. Focus on filling seats first - everything else follows.",
    },
    extraBody: {
      workedExample: "Example: A school with 100 students charging $10,000 tuition has $1M in tuition revenue. If per-pupil state funding is $8,500, that adds $850K. A $50K annual grant brings total to $1.9M. But note: if the grant ends in Year 3, Year 4 revenue drops to $1.85M unless enrollment grows to offset it. This is why enrollment-driven revenue is so important - it compounds, while grants are temporary.",
      benchmarkDetail: "Industry benchmarks: Charter schools typically receive $8,000-$15,000 per pupil in public funding depending on state. Private schools charge $8,000-$25,000 in tuition. Revenue per student below $8,000 is very lean. Schools with >70% of revenue from a single source need strong justification for that concentration.",
      glossaryTerms: "Per-Pupil Revenue: Total enrollment-driven revenue divided by total students. Revenue Concentration: The percentage of total revenue from your largest single source - above 80% warrants explanation. Earned Revenue: Income directly tied to delivering educational services, as opposed to philanthropic or grant income.",
      financingInsight: "If financing is ever part of your plan, banks rank revenue by reliability: (1) contracted per-pupil public funding, (2) tuition with documented collection rates, (3) multi-year grants with signed agreements, (4) annual fundraising. Keeping your strongest revenue sources front and center strengthens any application.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "revenue",
    dismissible: true,
    autoExpandFor: ["basics", "extra"],
    order: 1,
    highFriction: true,
    priority: "high",
  },
  enrollment_assumptions: {
    id: "enrollment_assumptions",
    title: "Enrollment Assumptions",
    body: {
      whatThisMeans: "Enrollment assumptions are your best estimate of how many students will attend your school each year for the next five years. This is the single most important input in your entire model - everything flows from it.",
      whyItMatters: "Demand is the engine. Every revenue line, every staffing decision, and every expense assumption flows from how many students you enroll. If enrollment falls short, the entire model breaks. This is the single most important assumption in any financial model.",
      healthyVsRisky: "Most new schools fill 40-65% of capacity in Year 1. Growth of 15-25% per year is considered strong and realistic. Jumping from 30 to 150 students in one year is worth questioning. What matters most: can you document the demand? Waitlist depth, letters of intent, recruitment pipeline, and retention rates are what make enrollment projections credible.",
      whatToDoNext: "I'd start with how many students you're confident you can enroll in Year 1 based on evidence - signed letters of intent, waitlist data, or community survey results. Then project realistic growth based on your recruitment capacity and retention expectations.",
    },
    extraBody: {
      workedExample: "Example: You start with 80 students in Year 1 with 85% retention. Year 2: 68 return + 32 new = 100 students. Year 3: 85 return + 35 new = 120. Year 4: 102 return + 28 new = 130. Year 5: 111 return + 29 new = 140. Notice how strong retention (85%) means you need fewer new students each year - retention compounds. At 75% retention, you'd need 52 new students in Year 2 just to reach 100, making growth much harder.",
      benchmarkDetail: "Enrollment benchmarks by school type: Urban charter schools average 85-95% of capacity by Year 3. Rural schools often take longer - 70-85% by Year 3. Private schools with no public funding typically fill slower. Year-over-year growth above 30% is rare and requires documented demand. Schools that grow too fast often face quality and staffing problems.",
      glossaryTerms: "Capacity Utilization: Enrolled students divided by your facility's maximum capacity. Retention Rate: Percentage of current students who re-enroll the following year. Net Enrollment Growth: New students minus departing students. Waitlist Depth: Number of qualified families waiting for a spot - the strongest evidence of demand.",
      financingInsight: "If financing is part of your plan, banks typically stress-test enrollment by 10-20%. The strongest models remain viable even at 70-80% of projected Year 1 enrollment - that kind of cushion gives everyone confidence.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "enrollment",
    dismissible: true,
    autoExpandFor: ["basics", "extra"],
    order: 2,
    highFriction: true,
    priority: "high",
  },
  tuition_assumptions: {
    id: "tuition_assumptions",
    title: "Tuition Assumptions",
    body: {
      whatThisMeans: "Your tuition assumptions include the amount you charge per student, how much you expect to collect, and how tuition changes over time. For private and independent schools, this is often the largest share of revenue.",
      whyItMatters: "Setting tuition too high can limit enrollment. Setting it too low can leave you short on revenue. Collection rates matter too - not every family pays the full amount on time. We'd encourage you to be realistic here rather than optimistic.",
      healthyVsRisky: "A collection rate of 90-95% is realistic for most schools. Planning for 100% collection is risky. Annual tuition increases of 2-4% are common and generally sustainable.",
      whatToDoNext: "I'd research what comparable schools in your area charge. Set a tuition level that balances affordability for families with your school's financial needs. If you're unsure, err slightly conservative - it's easier to adjust up than to recover from overestimating.",
    },
    extraBody: {
      workedExample: "Example: 120 students at $12,000 tuition = $1.44M gross tuition. With a 92% collection rate, actual collected tuition = $1.325M. The $115K gap is real - it comes from late payments, financial aid, and uncollectable accounts. If you modeled 100% collection, you'd be $115K short. Over 5 years with 3% annual tuition increases: Year 1: $12,000, Year 2: $12,360, Year 3: $12,731, Year 4: $13,113, Year 5: $13,506.",
      benchmarkDetail: "Tuition benchmarks: Urban independent schools average $12,000-$22,000. Suburban schools $15,000-$30,000. Faith-based schools $5,000-$12,000. Montessori programs $10,000-$18,000. Collection rates: New schools typically see 88-93% in Year 1, improving to 93-97% by Year 3 as families stabilize.",
      glossaryTerms: "Gross Tuition: The full tuition amount before financial aid or discounts. Net Tuition: What you actually collect after aid, discounts, and uncollected amounts. Collection Rate: The percentage of billed tuition you actually receive. Tuition Elasticity: How enrollment changes in response to tuition increases - typically a 5% increase reduces enrollment 2-3%.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "revenue",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 3,
    highFriction: false,
    priority: "standard",
  },
  grants_fundraising: {
    id: "grants_fundraising",
    title: "Grants and Fundraising",
    body: {
      whatThisMeans: "This includes grants from foundations, government programs, and individual donations. Some of this funding may be restricted to specific purposes, while other funds can be used for general operations.",
      whyItMatters: "Grants and fundraising can be valuable, but they're inherently uncertain - competitive, time-limited, and subject to donor priorities. We always recommend building a model anchored to earned revenue that scales with enrollment, not to fundraising outcomes.",
      healthyVsRisky: "If grants make up more than 30% of your recurring operating revenue, the model depends on fundraising rather than demand. A healthy model treats philanthropy as supplemental - accelerating growth or funding specific programs - not as the foundation that keeps the lights on.",
      whatToDoNext: "I'd list only the grants and fundraising you have strong reason to expect. Separate one-time startup grants from ongoing support. Focus the model on earned revenue first, then layer in philanthropic upside.",
    },
    extraBody: {
      workedExample: "Example: A school with $1.5M total revenue receives a $200K startup grant (Year 1 only) and expects $75K/year in annual fundraising. Year 1 grant dependency: 13%. Year 2 (no startup grant): fundraising is 5% of revenue - healthy. But if you budgeted the $200K as recurring, Year 2 shows a $200K hole. Always model grants as ending in their last confirmed year.",
      benchmarkDetail: "Grant benchmarks: Federal CSP (Charter School Program) grants provide $150K-$750K over 3 years. State startup grants vary widely ($50K-$500K). Foundation grants for education typically range $10K-$100K. Annual fund targets for new schools: $25K-$75K in Year 1, growing 10-15% annually. Mature schools raise $50-$150 per student annually.",
      glossaryTerms: "Restricted Funds: Grant money that must be spent on specific purposes (e.g., technology, professional development). Unrestricted Funds: Donations that can be used for any operational purpose. Grant Cliff: The year a multi-year grant ends, creating a sudden revenue drop if not replaced. Cost Sharing: When a grant requires the school to fund a portion of the project from its own resources.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "revenue",
    dismissible: true,
    autoExpandFor: [],
    order: 4,
    highFriction: false,
    priority: "standard",
  },
  payroll: {
    id: "payroll",
    title: "Payroll",
    body: {
      whatThisMeans: "Payroll is the total cost of compensating your team - salaries, benefits, payroll taxes, and any other personnel-related expenses. This is almost always the largest single expense category for a school.",
      whyItMatters: "Personnel costs typically represent 50-65% of a school's total budget. If payroll grows faster than revenue, the school will face financial pressure quickly. Getting staffing right is one of the most important parts of your financial model - we can't stress this enough.",
      healthyVsRisky: "Staffing costs under 55% of revenue are generally healthy. Between 55-65% is manageable but worth watching. Above 65% is a warning sign that the school may be overstaffed relative to its revenue.",
      whatToDoNext: "I'd start with your essential roles and build up. Consider which positions can be part-time or shared in the early years. Make sure your staffing plan grows in step with enrollment - that alignment is critical.",
    },
    extraBody: {
      workedExample: "Example: A school with $1.2M revenue and 10 staff members. Base salaries total $650K. Add 25% for benefits and payroll taxes (FICA 7.65%, health insurance ~$6K/employee, workers comp ~2%): loaded cost = $812K. That's 68% of revenue - a warning zone. Reducing to 9 staff saves ~$81K loaded, dropping to 61% - much healthier. Each additional FTE at $65K salary actually costs ~$81K loaded.",
      benchmarkDetail: "Staffing cost benchmarks: Charter schools average 55-65% of revenue on personnel. High-performing networks target 50-55%. Teacher salaries vary widely: $35K-$65K depending on region. Administrative salaries: Head of School $80K-$130K, Operations Manager $45K-$70K. Loaded cost multiplier (benefits + taxes): typically 1.25x-1.35x of base salary.",
      glossaryTerms: "Loaded Cost: Total compensation including salary, benefits, and employer-paid taxes. FTE (Full-Time Equivalent): A measure of staff commitment - 1.0 = full-time, 0.5 = half-time. Student-to-Teacher Ratio: Total students divided by instructional FTE - most schools target 12:1 to 20:1. Benefits Load: The percentage added to base salary for health insurance, retirement, and payroll taxes - typically 25-35%.",
      financingInsight: "Staffing above 65% of revenue leaves very little room for facilities, debt, and reserves. If financing is part of your plan, banks look at whether staffing scales with enrollment - building lean and growing thoughtfully signals strong leadership.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "staffing",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 5,
    highFriction: true,
    priority: "high",
  },
  occupancy_rent: {
    id: "occupancy_rent",
    title: "Occupancy and Rent",
    body: {
      whatThisMeans: "Occupancy costs include your rent or mortgage, utilities, maintenance, insurance, and any other facility-related expenses. For many schools, this is the second-largest expense after payroll.",
      whyItMatters: "Facility costs are usually fixed - they don't change much whether you have 20 students or 100. That makes them especially important for new schools that are still growing enrollment. We see facility costs trip up founders who lock into expensive leases before enrollment proves out.",
      healthyVsRisky: "Occupancy costs between 10-20% of revenue are typical. Above 25% can put pressure on your budget, especially in the early years when enrollment is ramping up. Lease terms and facility costs deserve careful attention.",
      whatToDoNext: "If you have a location, enter your actual costs. If you're still searching, use estimates based on comparable spaces in your area. I'd seriously consider whether sharing space or starting smaller could reduce early-year risk.",
    },
    extraBody: {
      workedExample: "Example: A school leases 8,000 sqft at $15/sqft = $120K/year rent. Add utilities ($18K), insurance ($5K), maintenance ($8K) = $151K total occupancy. With Year 1 revenue of $800K, occupancy is 19% of revenue - acceptable but tight. By Year 3, with revenue at $1.2M, the same $151K is only 13% - much healthier. This shows why fixed facility costs become less burdensome as enrollment grows.",
      benchmarkDetail: "Facility cost benchmarks: Lease rates for school-suitable space range $8-$25/sqft depending on market. Utilities run $1.50-$3.00/sqft. Schools need 50-80 sqft per student for classrooms plus 30-50% for common areas. Total facility cost per student: $1,200-$3,000/year is typical. Schools paying above $3,500/student in facility costs are in the danger zone.",
      glossaryTerms: "Triple Net Lease (NNN): A lease where the tenant pays base rent plus property taxes, insurance, and maintenance - common for school spaces. CAM Charges: Common Area Maintenance fees in shared buildings. Occupancy Rate: Your facility cost as a percentage of total revenue. Tenant Improvement (TI) Allowance: Money the landlord provides for build-out - negotiate this aggressively for school conversions.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "expenses",
    dismissible: true,
    autoExpandFor: [],
    order: 6,
    highFriction: false,
    priority: "standard",
  },
  program_expenses: {
    id: "program_expenses",
    title: "Program Expenses",
    body: {
      whatThisMeans: "Program expenses cover the costs directly related to running your educational program: curriculum materials, textbooks, technology, supplies, field trips, assessments, and professional development for staff.",
      whyItMatters: "These costs directly affect the quality of education you can deliver. Underfunding your program can hurt student outcomes and make it harder to attract and retain families. But over-spending before you have the revenue to support it can strain your budget. It's a balance we help founders navigate.",
      healthyVsRisky: "Most schools spend $300-800 per student on instructional materials and $150-300 per student on technology. Spending significantly above or below these ranges is worth examining.",
      whatToDoNext: "I'd start with your core instructional needs and add from there. Consider what you truly need in Year 1 versus what can be phased in as the school grows.",
    },
    extraBody: {
      workedExample: "Example: A school with 100 students budgets $500/student for curriculum ($50K), $200/student for technology ($20K), $100/student for supplies ($10K), and $50/student for assessments ($5K). Total program expenses = $85K or $850/student. With 2% annual inflation, Year 5 costs rise to $92K. Adding 40 new students by Year 5 increases to $119K - but per-student cost stays flat because these are largely variable costs.",
      benchmarkDetail: "Program expense benchmarks by category: Curriculum/textbooks $300-$600/student (higher for STEM or specialty programs). Technology (1:1 device programs) $200-$400/student including replacement cycles. Assessment platforms $30-$75/student. Classroom supplies $75-$150/student. Field trips and enrichment $50-$200/student. Total program costs typically run 5-10% of total budget.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "expenses",
    dismissible: true,
    autoExpandFor: [],
    order: 7,
    highFriction: false,
    priority: "standard",
  },
  operating_surplus_deficit: {
    id: "operating_surplus_deficit",
    title: "Operating Surplus or Deficit",
    body: {
      whatThisMeans: "Your operating surplus (or deficit) is the difference between your total revenue and total expenses for a given year. A surplus means you brought in more than you spent. A deficit means expenses exceeded revenue.",
      whyItMatters: "A small surplus is the goal for most schools, especially nonprofits. It shows the school can sustain itself and build reserves. Repeated deficits signal that the current model isn't financially sustainable without changes. We always look at this trend across all five years.",
      healthyVsRisky: "New schools often run a small deficit in Year 1 as they ramp up - that's normal. By Year 2 or 3, most viable models show a positive margin. A margin of 5-15% by Year 5 is a strong sign your school is on solid footing.",
      whatToDoNext: "If your model shows persistent deficits, I'd look at the biggest cost drivers first: staffing, rent, and enrollment. Small changes in these areas can have a meaningful impact on your bottom line.",
    },
    extraBody: {
      workedExample: "Example: Year 1: Revenue $900K - Expenses $950K = -$50K deficit (5.6% margin). Year 2: $1.1M - $1.05M = +$50K surplus (4.5%). Year 3: $1.3M - $1.15M = +$150K (11.5%). This trajectory is textbook healthy - a modest Year 1 deficit followed by growing surpluses. The cumulative position turns positive mid-Year 2. Contrast with a model showing -$50K, -$30K, -$10K, +$5K, +$15K - technically profitable by Year 4, but razor-thin margins leave no room for surprises.",
      benchmarkDetail: "Operating margin benchmarks: Year 1 deficit up to 10% is acceptable if covered by startup reserves. By Year 3, target 5-10% operating margin. By Year 5, 8-15% margin is strong. Nonprofit schools above 20% margin may face questions about mission alignment. Schools that never achieve positive margin within 5 years have a structural cost problem.",
      glossaryTerms: "Operating Margin: Net income divided by total revenue, expressed as a percentage. Cumulative Surplus/Deficit: The running total of all surpluses and deficits across years - shows your overall financial trajectory. Breakeven Point: The year in which annual revenue first equals or exceeds annual expenses.",
      financingInsight: "If financing is part of your plan, banks want to see a clear path to profitability within 2-3 years. A Year 1 deficit is understandable if startup costs are clearly identified and non-recurring. Persistent deficits beyond Year 2 may signal a structural challenge worth addressing.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "review",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 8,
    highFriction: false,
    priority: "high",
  },
  cash_flow: {
    id: "cash_flow",
    title: "Cash Flow",
    body: {
      whatThisMeans: "Cash flow tracks the actual movement of money in and out of your school over time. Unlike your annual budget, cash flow shows when money arrives and when it leaves - which can be very different things.",
      whyItMatters: "A school can have a balanced annual budget but still run out of cash in certain months. This happens when expenses come due before revenue arrives, like paying rent in August before tuition payments start in September. We see this catch founders off guard more than almost anything else.",
      healthyVsRisky: "Having at least 2-3 months of operating expenses in cash at all times is a good target. If your cash dips below one month of expenses at any point, that's a risk that needs attention.",
      whatToDoNext: "I'd look at the timing of your major revenue and expenses. If there's a gap, consider how you'll bridge it - whether through a line of credit, earlier payment collection, or building up reserves.",
    },
    extraBody: {
      workedExample: "Example: Monthly expenses are $80K (payroll $55K, rent $12K, other $13K). Tuition arrives over 10 months ($100K/month), but July-August have $0 tuition. In July, you pay $80K in expenses with $0 revenue. Starting cash of $50K minus July expenses = -$30K. You'd need at least $160K in starting cash to survive a 2-month gap. This is why timing matters more than annual totals - your annual budget balances, but your July bank account is empty.",
      benchmarkDetail: "Cash flow benchmarks: Schools should maintain a minimum cash balance equal to 45-60 days of operating expenses at all times. The most dangerous months are typically July-September for schools starting in fall (expenses hit before revenue). Schools with per-pupil funding often receive payments quarterly or with a 30-60 day lag. Tuition-based schools with 10-month payment plans have a predictable 2-month gap.",
      glossaryTerms: "Cash Trough: The lowest cash balance your school hits at any point during the projection period - this is the number that determines whether you survive. Operating Cash Cycle: The time between when you pay expenses and when you collect revenue. Line of Credit: A pre-approved borrowing facility that lets you draw cash during lean months and repay when revenue arrives.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "review",
    dismissible: true,
    autoExpandFor: [],
    order: 9,
    highFriction: false,
    priority: "standard",
  },
  ending_cash: {
    id: "ending_cash",
    title: "Ending Cash",
    body: {
      whatThisMeans: "Ending cash is the amount of money your school has at the end of a given period, after accounting for all the cash that came in and went out. Think of it as your bank balance at the end of the month or year.",
      whyItMatters: "Ending cash tells you whether your school can actually pay its bills. Even if your annual budget shows a surplus, you need enough cash on hand to cover payroll, rent, and other expenses as they come due. This is one of the first things any reviewer will look at.",
      healthyVsRisky: "Ending cash should never go negative - that means you can't cover your obligations. Having 2-3 months of expenses in ending cash provides a reasonable safety cushion.",
      whatToDoNext: "If ending cash drops below zero in any month, I'd review when your revenue arrives versus when your largest expenses are due. Adjust timing assumptions or plan for a startup reserve - even a small one makes a big difference.",
    },
    extraBody: {
      workedExample: "Example: Starting cash $100K. Year 1 net income -$40K → ending cash $60K (1 month of expenses if monthly expenses are $60K - dangerously thin). Year 2 net income +$30K → ending cash $90K (1.5 months - better). Year 3 net income +$80K → ending cash $170K (2.5 months - approaching healthy). The key insight: even with a Year 1 deficit, adequate starting cash prevents a crisis. Without that $100K cushion, cash goes negative by month 8.",
      benchmarkDetail: "Ending cash targets by year: Year 1 ending cash should be at least 1 month of Year 2 operating expenses. By Year 3, target 2-3 months. By Year 5, 3-6 months is considered strong. Schools entering Year 2 with less than $30K ending cash are in the danger zone regardless of their budget projections.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "review",
    dismissible: true,
    autoExpandFor: [],
    order: 10,
    highFriction: false,
    priority: "standard",
  },
  reserves: {
    id: "reserves",
    title: "Reserves",
    body: {
      whatThisMeans: "Reserves are the savings your school sets aside to handle unexpected costs or revenue shortfalls. This is money that's available but not earmarked for day-to-day operations - your financial safety net.",
      whyItMatters: "Schools without adequate reserves are vulnerable to surprises like enrollment drops, facility repairs, or delayed grant payments. Reserves are a key indicator of financial health - we always look at this when evaluating a model.",
      healthyVsRisky: "Best practice is to build toward 3-6 months of operating expenses in reserves. Schools with less than one month of reserves are in a risky position.",
      whatToDoNext: "If you're starting without reserves, I'd build a plan to accumulate them over time. Even small surpluses set aside each year add up. Consider including a reserve target in your model's assumptions - it shows thoughtful planning.",
    },
    extraBody: {
      workedExample: "Example: Monthly operating expenses are $75K. Target reserve: 3 months = $225K. If your model generates $50K surplus per year, it takes 4.5 years to reach your reserve target. But if you start with a $75K startup reserve and add $50K/year: Year 1: $125K (1.7 months), Year 2: $175K (2.3 months), Year 3: $225K (3.0 months - target reached). Starting with even a modest reserve dramatically accelerates your path to financial stability.",
      benchmarkDetail: "Reserve benchmarks: NACSA (National Association of Charter School Authorizers) recommends 45 days of cash on hand minimum. If financing is part of your plan, loan covenants often require 60-90 days. Highly rated schools maintain 4-6 months. Schools in financial distress typically have <15 days. Reserve accumulation rate: plan to add 3-5% of revenue annually until target is reached.",
      glossaryTerms: "Operating Reserve: Cash set aside for unexpected expenses or revenue shortfalls - measured in months of operating expenses. Board-Designated Reserve: Reserves the board has earmarked for specific purposes (e.g., facility expansion, technology refresh). Days of Cash on Hand: Ending cash divided by daily operating expenses - a more precise measure than months of reserves.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "review",
    dismissible: true,
    autoExpandFor: [],
    order: 11,
    highFriction: false,
    priority: "standard",
  },
  budget_vs_actual: {
    id: "budget_vs_actual",
    title: "Budget vs Actual",
    body: {
      whatThisMeans: "Budget vs actual compares what you planned to spend and earn against what actually happened. This is how you measure whether your financial model held up in practice.",
      whyItMatters: "No budget is perfect on the first try. Tracking budget vs actual helps you identify where your assumptions were off so you can improve future projections. Boards and reviewers expect to see this kind of accountability - and honestly, it's one of the best habits you can build.",
      healthyVsRisky: "Small variances (under 5-10%) are normal and expected. Large, repeated variances in the same direction suggest your assumptions need updating. The worst outcome is not tracking this at all.",
      whatToDoNext: "I'd plan to compare your budget against actual results monthly or quarterly once the school is operating. Use what you learn to update your projections and make better decisions going forward.",
    },
    extraBody: {
      workedExample: "Example: You budgeted $55K/month for payroll but actual is $58K due to a mid-year hire. That's a 5.5% variance - manageable if offset elsewhere. But if revenue is also 8% below budget ($92K vs $100K), the combined effect is -$11K/month or -$132K/year. This is why tracking matters: individually, each variance seems small, but together they create a serious cash crunch by month 9.",
      benchmarkDetail: "Variance tracking benchmarks: Review budget vs actual monthly. Flag any line item >10% over budget. Revenue variances below -5% should trigger a management response. Most schools find their biggest variances in: enrollment (and therefore revenue), substitute teacher costs, and utility expenses. After Year 1, your budget accuracy should improve - Year 2 budgets are typically within 5% of actuals.",
    },
    audienceLevel: ["extra"],
    relatedSection: "review",
    dismissible: true,
    autoExpandFor: [],
    order: 12,
    highFriction: false,
    priority: "standard",
  },
  fundraising_strategy: {
    id: "fundraising_strategy",
    title: "Fundraising & Philanthropy",
    body: {
      whatThisMeans: "Fundraising includes annual funds, individual donations, events, and grants from foundations or government programs. For faith-affiliated schools, it may also include parish subsidies or congregation support.",
      whyItMatters: "Philanthropy can provide crucial early-stage funding, but it's inherently uncertain and time-limited. The strongest models are anchored to enrollment-driven revenue. For-profit schools face additional complexity - donors can't claim tax deductions for gifts to a for-profit entity without a fiscal sponsor arrangement.",
      healthyVsRisky: "Philanthropy as 10-25% of total revenue is supplemental and healthy. Above 30% signals dependence on uncertain income. If you're a for-profit school fundraising through a fiscal sponsor, I'd budget for the sponsor's fee - typically 5-10% of the philanthropic revenue they process, entered as an annual dollar amount.",
      whatToDoNext: "I'd start with your most certain fundraising sources. If you're a for-profit school planning to fundraise, establish a fiscal sponsorship early - approval takes 4-8 weeks. Estimate your annual philanthropy, multiply by the sponsor's fee rate (5-10%), and enter that dollar amount as your Fiscal Sponsor Fee expense.",
    },
    extraBody: {
      workedExample: "Example: You plan to raise $150K in Year 1 through a gala ($50K), individual donors ($60K), and a foundation grant ($40K). Realistic collection: galas typically net 60% after event costs = $30K. Individual donors: new schools convert 40-50% of pledges = $24K-$30K. Foundation grant: if approved, 100% = $40K. Realistic total: $94K-$100K vs. the planned $150K. Budget the conservative number and treat the upside as bonus.",
      benchmarkDetail: "Fundraising benchmarks by channel: Annual galas net 50-65% after expenses. Online campaigns convert 2-4% of recipients. Major donor cultivation takes 12-18 months. Foundation grants have 15-25% win rates. Cost to raise $1: events cost $0.30-$0.50 to raise $1, individual giving costs $0.15-$0.25, grants cost $0.05-$0.10. New schools should expect 30-50% less fundraising in Year 1 than established schools.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "revenue",
    dismissible: true,
    autoExpandFor: [],
    order: 4.5,
    highFriction: false,
    priority: "standard",
  },
  fixed_vs_variable: {
    id: "fixed_vs_variable",
    title: "Fixed vs Variable Costs",
    body: {
      whatThisMeans: "Fixed costs stay roughly the same regardless of how many students you have, like rent and insurance. Variable costs change with enrollment, like instructional materials and food service.",
      whyItMatters: "Understanding this distinction helps you plan for different enrollment scenarios. If most of your costs are fixed, a drop in enrollment hits much harder because those costs don't shrink with fewer students. We think this is one of the most important concepts for new founders to internalize.",
      healthyVsRisky: "A healthy cost structure has a mix of both. Schools with very high fixed costs relative to revenue need higher enrollment certainty to be sustainable. Schools with more variable costs have more flexibility if enrollment comes in lower than planned.",
      whatToDoNext: "I'd look at your expense categories and identify which are fixed and which change with enrollment. This helps you understand your breakeven point and what happens if enrollment comes in lower than planned.",
    },
    extraBody: {
      workedExample: "Example: Your school has $600K in fixed costs (rent $120K, admin salaries $280K, insurance $8K, loan payments $48K, utilities $18K, other fixed $126K) and $200K in variable costs ($2,000/student × 100 students for instructional supplies, food, etc.). Total expenses: $800K. Revenue per student: $10,000. Break-even enrollment: $600K ÷ ($10,000 - $2,000) = 75 students. Every student above 75 contributes $8,000 to your surplus. At 100 students, surplus = $200K.",
      benchmarkDetail: "Cost structure benchmarks: Schools typically have 65-80% fixed costs and 20-35% variable costs. Higher fixed cost ratios mean higher breakeven enrollment. Schools with fixed costs below 60% have more downside protection but may face quality concerns. Key fixed costs: leadership salaries, rent, insurance, debt service. Key variable costs: instructional materials, food service, per-student technology.",
      glossaryTerms: "Fixed Cost: An expense that doesn't change with enrollment (rent, admin salaries, insurance). Variable Cost: An expense that scales with enrollment (per-student supplies, food service). Contribution Margin: Revenue per student minus variable cost per student - what each additional student contributes to covering fixed costs. Operating Leverage: A school with high fixed costs and low variable costs has high operating leverage - profits grow quickly above breakeven but losses mount quickly below it.",
    },
    audienceLevel: ["extra"],
    relatedSection: "expenses",
    dismissible: true,
    autoExpandFor: [],
    order: 13,
    highFriction: false,
    priority: "standard",
  },
  facility_occupancy: {
    id: "facility_occupancy",
    title: "Occupancy Costs",
    body: {
      whatThisMeans: "Occupancy costs are everything related to your physical space - rent or mortgage, utilities, insurance, and maintenance. Together, these form your second-largest expense category after payroll.",
      whyItMatters: "Facility costs are almost entirely fixed - they don't shrink when enrollment is low. Locking into an expensive lease before enrollment proves out is one of the most common financial mistakes we see. Your occupancy-to-revenue ratio is worth watching closely.",
      healthyVsRisky: "Total occupancy costs between 10-20% of revenue are typical for schools. Above 25% puts real pressure on your budget, especially in the early years. If your rent alone exceeds 15% of projected Year 1 revenue, consider a smaller or shared space.",
      whatToDoNext: "Add up your monthly rent, annual utilities, insurance, and maintenance to see your total occupancy cost. Compare it against your Year 1 revenue projection. If it's above 20%, explore options to reduce facility costs before committing.",
    },
    extraBody: {
      workedExample: "Example: Two facility options. Option A: 10,000 sqft at $18/sqft = $180K/year. Option B: 6,000 sqft shared space at $14/sqft = $84K/year with option to expand. With Year 1 revenue of $800K, Option A = 22.5% of revenue (risky), Option B = 10.5% (healthy). Option B saves $96K/year - enough to fund 1.5 additional teacher positions. Even if you outgrow Option B by Year 3, the savings compound: $192K over 2 years of lower rent.",
      benchmarkDetail: "Facility cost benchmarks by market: Urban schools in high-cost markets (NYC, SF, DC) often pay $20-$35/sqft. Suburban markets: $10-$20/sqft. Rural or church-shared spaces: $5-$12/sqft. Schools should plan for 50-80 sqft per student for classrooms, plus 30-50% additional for common areas, offices, and storage. A 100-student school needs roughly 8,000-12,000 total sqft.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "facilities",
    dismissible: true,
    autoExpandFor: ["basics", "extra"],
    order: 13.5,
    highFriction: true,
    priority: "high",
  },
  facility_maintenance: {
    id: "facility_maintenance",
    title: "Maintenance & Repairs",
    body: {
      whatThisMeans: "Maintenance covers everything that keeps your building functional and safe - janitorial services, HVAC upkeep, plumbing and electrical repairs, grounds maintenance, and general wear-and-tear fixes. This is separate from your rent or mortgage.",
      whyItMatters: "Deferred maintenance is one of the most common budget mistakes we see. Founders skip this line item to keep costs low, then face emergency repairs that blow through their reserves. A model with zero maintenance budget raises concerns for any reviewer.",
      healthyVsRisky: "Plan for 2-4% of your facility's annual value, or $2-5 per square foot per year. Schools spending less than $1/sqft on maintenance are deferring costs that will eventually come due. Every school needs a maintenance line item - don't skip it.",
      whatToDoNext: "If you own or lease, ask your landlord or property manager what typical annual maintenance runs. For a leased space, $2,000-5,000/year is a reasonable starting point for a small school. Include a small buffer for unexpected repairs - they always come.",
    },
    extraBody: {
      workedExample: "Example: Your school occupies an 8,000 sqft building valued at $500K. At 3% of value: $15K/year maintenance budget. Breakdown: Janitorial contract $6K, HVAC service $3K, general repairs reserve $4K, grounds/snow $2K. In Year 3, the HVAC fails - replacement cost $12K. If you'd budgeted $0 for maintenance, this single event wipes out your entire quarterly surplus. With the $15K budget, you have $4K in reserve plus can redirect from other maintenance categories.",
      benchmarkDetail: "Maintenance cost benchmarks: Janitorial services $0.75-$1.50/sqft. HVAC maintenance $2,000-$5,000/year for a small building. Roof repairs average $5K-$15K when needed. Schools should set aside 10-15% of annual maintenance budget for emergency repairs. Age of building matters: pre-1990 buildings typically cost 30-50% more to maintain.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "facilities",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 14,
    highFriction: false,
    priority: "standard",
  },
  food_service: {
    id: "food_service",
    title: "Food & Meal Service",
    body: {
      whatThisMeans: "Food service covers the cost of providing meals to students - whether you run your own kitchen, contract with a vendor, or participate in the National School Lunch Program (NSLP). This is a per-student cost that scales with enrollment.",
      whyItMatters: "Meal programs can be a significant expense or a revenue-neutral service depending on your approach. Schools participating in NSLP receive federal reimbursement that can offset most costs. Schools providing meals without reimbursement should budget carefully - food costs add up fast.",
      healthyVsRisky: "NSLP reimbursement covers $3.50-4.50 per free lunch. If you're self-funding, expect $4-7 per student per day, or $700-1,300 per student annually. Schools that promise meals without budgeting for them often face mid-year shortfalls.",
      whatToDoNext: "Decide whether you'll participate in NSLP (most charter and public schools do) or self-fund meals. If you're not providing meals, enter $0 - but note that some charter authorizers require a meal program. If providing meals, get vendor quotes or estimate per-student daily costs.",
    },
    extraBody: {
      workedExample: "Example: 100 students, 180 school days. Self-funded meals at $5/student/day = $90K/year. With NSLP and 70% free/reduced-price eligibility: Reimbursement at $4.00/meal × 70 students × 180 days = $50.4K. Your cost: $90K - $50.4K = $39.6K net cost, or ~$396/student. That's a 56% reduction from self-funding. If you're eligible for NSLP, participation dramatically changes your food service economics.",
      benchmarkDetail: "Meal program benchmarks: NSLP free lunch reimbursement: $4.09 (2024 rate, increases annually). Reduced-price: $3.69. Paid: $0.39. Vendor-contracted meal costs: $4.50-$7.00 per meal depending on menu and region. Schools with >60% free/reduced-price eligible students often break even on food service through NSLP. Breakfast programs add $1.50-$2.50 per student per day.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "facilities",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 15,
    highFriction: false,
    priority: "standard",
  },
  transportation: {
    id: "transportation",
    title: "Transportation",
    body: {
      whatThisMeans: "Transportation costs include school bus contracts, ride-share partnerships, parent stipends, or any other arrangement to get students to and from school. Some states require charter schools to provide transportation; others leave it optional.",
      whyItMatters: "Transportation can be a make-or-break factor for enrollment. Families who can't get their children to school won't enroll. But bus contracts are expensive and often locked in for a full year regardless of ridership. We see founders underestimate this cost or commit to transportation they can't sustain.",
      healthyVsRisky: "Full bus service typically costs $800-2,000 per student per year depending on distance and region. Ride-share or stipend models run $500-1,000. If transportation is required by your charter or state law, budget for it - $0 isn't an option.",
      whatToDoNext: "Check whether your state or authorizer requires you to provide transportation. If so, get quotes from local bus companies early - prices vary significantly by region. If optional, consider whether offering transportation would meaningfully increase your enrollment.",
    },
    extraBody: {
      workedExample: "Example: A school needs to transport 60 of its 100 students. Option A: Full bus contract, 2 routes at $45K each = $90K/year ($1,500/transported student). Option B: Parent transit stipends at $600/student = $36K/year. Option C: Partnership with public transit for $400/student = $24K. The cost difference is enormous - Option A costs 3.75x more than Option C. But Option A may be required by your authorizer or state law.",
      benchmarkDetail: "Transportation benchmarks: Bus contracts cost $35K-$65K per route per year. Average route serves 30-45 students. Fuel cost increases of 5-8% annually are common. States requiring charter transportation: some reimburse at $500-$1,200/student, others require schools to self-fund. Schools spending >8% of revenue on transportation should evaluate alternatives.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "facilities",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 16,
    highFriction: false,
    priority: "standard",
  },
  professional_development: {
    id: "professional_development",
    title: "Professional Development",
    body: {
      whatThisMeans: "Professional development (PD) covers teacher training, conferences, certifications, coaching, and any investment in growing your staff's skills. This includes both external programs and internal training time.",
      whyItMatters: "Schools that invest in PD retain teachers longer and deliver better outcomes. A PD budget signals that leadership takes quality seriously. Skipping PD to save money is a false economy - it leads to higher turnover, which costs far more.",
      healthyVsRisky: "Most schools budget $500-1,500 per staff member per year for PD. Less than $200 per person signals underinvestment. Some charter authorizers require a minimum PD budget as a condition of the charter.",
      whatToDoNext: "Budget at least $500 per staff member for Year 1. As revenue grows, increase PD spending - it's one of the best investments you can make in school quality and staff retention.",
    },
    extraBody: {
      workedExample: "Example: 12 staff members at $1,000/person = $12K PD budget. Allocation: 4 teachers attend a $2,000 national conference ($8K), remaining $4K covers online PD subscriptions for all staff. Teacher turnover costs $8K-$15K per departure (recruiting, training, lost productivity). If PD investment prevents even 1 teacher from leaving, it pays for itself. Schools with robust PD programs see 15-25% lower turnover than those without.",
      benchmarkDetail: "PD spending benchmarks: High-performing charter networks spend $1,500-$3,000 per staff member. Traditional districts average $500-$800. Best practice: allocate 1-3% of total personnel budget to PD. Required PD hours vary by state: typically 15-30 hours/year for teacher certification maintenance.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "facilities",
    dismissible: true,
    autoExpandFor: [],
    order: 17,
    highFriction: false,
    priority: "standard",
  },
  insurance_coverage: {
    id: "insurance_coverage",
    title: "Insurance",
    body: {
      whatThisMeans: "School insurance typically includes general liability, property insurance, directors & officers (D&O), workers' compensation, and potentially umbrella coverage. This is a non-negotiable operating cost for any school.",
      whyItMatters: "Operating without adequate insurance is both a legal risk and a non-starter for any serious financial plan. Insurance costs tend to escalate 5-8% annually, which founders often forget to factor in. We've seen models that budget Year 1 insurance correctly but don't account for increases.",
      healthyVsRisky: "Most small schools pay $3,000-8,000 annually for a basic insurance package. Schools with transportation or athletics should budget higher ($8,000-15,000). A $0 insurance budget will immediately raise questions from anyone reviewing your model.",
      whatToDoNext: "Get quotes from 2-3 insurance brokers who specialize in schools - they'll know the coverage requirements for your state. Budget the Year 1 quote and plan for 5-8% annual increases in your assumptions.",
    },
    extraBody: {
      workedExample: "Example: Year 1 insurance package: General liability $2,500, property $1,200, D&O $1,800, workers' comp $2,000, umbrella $1,500 = $9,000 total. With 6% annual increases: Year 2: $9,540, Year 3: $10,112, Year 4: $10,719, Year 5: $11,362. Over 5 years, insurance costs $50,733 - 13% more than if you'd assumed flat pricing. Always escalate insurance in your projections.",
      benchmarkDetail: "Insurance cost benchmarks by type: General liability $1,500-$4,000. Property insurance $800-$3,000 (depends on building value). D&O $1,200-$3,000. Workers' comp 1.5-3% of payroll. Umbrella/excess liability $1,000-$3,000. Schools with buses need commercial auto insurance: $3,000-$8,000 per vehicle. Total insurance for a 100-student school: $8,000-$18,000.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "facilities",
    dismissible: true,
    autoExpandFor: [],
    order: 18,
    highFriction: false,
    priority: "standard",
  },
  debt_service: {
    id: "debt_service",
    title: "Debt Service",
    body: {
      whatThisMeans: "Debt service is the total amount you pay on any loans - principal plus interest. This includes loans for building renovations, equipment, working capital, or any other borrowed funds.",
      whyItMatters: "Debt service is a fixed obligation that must be paid regardless of enrollment or revenue. Your Debt Service Coverage Ratio (DSCR) - available cash flow divided by debt payments - tells you whether your school can comfortably meet its loan obligations.",
      healthyVsRisky: "A DSCR of 1.2x or higher is considered healthy - meaning you have 20% more cash flow than needed to cover debt. Below 1.0x means you can't cover your payments from operations. If you're applying for financing, most banks require at least 1.15x DSCR.",
      whatToDoNext: "If you plan to take on debt, enter the loan details accurately. If your DSCR comes out below 1.2x, consider whether you can reduce the loan amount, extend the term, or grow revenue faster. Don't take on debt your model can't support.",
    },
    extraBody: {
      workedExample: "Example: You borrow $500K at 7% interest over 10 years. Annual payment: $71,187 ($35,000 interest in Year 1 + $36,187 principal). Your Year 1 net operating income (before debt service) is $85,000. DSCR = $85,000 ÷ $71,187 = 1.19x - just below the 1.2x threshold most banks look for. Adding 10 more students at $10K revenue each would push net income to $165K and DSCR to 2.32x. Small enrollment changes have outsized DSCR impact.",
      benchmarkDetail: "Debt benchmarks for schools: Interest rates for charter school loans: 5-9% (varies with credit quality and collateral). Typical loan terms: 7-15 years for facility loans, 3-5 years for working capital. Maximum recommended debt: total debt service should not exceed 15% of revenue. Typical bank DSCR requirements: minimum 1.15x-1.25x. Some CDFIs (Community Development Financial Institutions) accept lower DSCR for mission-aligned schools.",
      glossaryTerms: "DSCR (Debt Service Coverage Ratio): Net operating income divided by total annual debt payments. A DSCR of 1.5x means you earn 50% more than you owe in loan payments. Principal: The portion of your loan payment that reduces the outstanding balance. Amortization: The schedule by which loan principal is paid down over time. Covenant: A condition in your loan agreement (like maintaining 1.2x DSCR) that you must meet or risk default.",
      financingInsight: "If you're applying for financing, DSCR is the single most important metric banks evaluate. Below 1.0x means the school can't cover debt from operations. Between 1.0x-1.15x may require additional security. Above 1.25x gives confidence that your school can handle debt even if enrollment dips 10-15%.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "facilities",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 19,
    highFriction: true,
    priority: "high",
  },
  narrative_enrollment_strategy: {
    id: "narrative_enrollment_strategy",
    title: "Writing Your Enrollment Strategy",
    body: {
      whatThisMeans: "This section explains how you'll fill seats - your marketing channels, community outreach, waitlist strategy, and evidence of demand. Anyone reviewing your model will read this to assess whether your enrollment projections are realistic or aspirational.",
      whyItMatters: "Enrollment strategy is the first thing reviewers look at because every revenue line depends on it. They want to see specific, evidence-backed plans - not vague optimism. A founder who can articulate exactly how 50 families will find and choose their school is far more credible than one who writes 'we expect strong community interest.'",
      healthyVsRisky: "Strong: 'We have 35 signed letters of intent and a waitlist of 12 families from our community info sessions. Our marketing plan includes partnerships with 3 local churches and a monthly open house series.' Weak: 'We expect families will be interested because our program is unique and there's demand in the area.'",
      whatToDoNext: "Name your specific recruitment channels (info sessions, church partnerships, social media campaigns, community events). Cite evidence: letters of intent, waitlist numbers, survey results, or pre-registration counts. If you don't have evidence yet, describe your plan to build it before opening day.",
    },
    extraBody: {
      workedExample: "Example enrollment strategy: 'Target: 80 students in Year 1. Evidence: 47 signed letters of intent as of March 2025. Sources: 6 community info sessions (avg. 22 attendees, 35% conversion to LOI), partnership with First Baptist Church (12 LOIs from congregation), Facebook/Instagram campaign (800 clicks, 15% to info session). Conversion funnel: 800 digital leads → 180 info session attendees → 63 LOIs → projected 80 enrolled (127% of LOI typically enroll when waitlisted peers confirm).'",
      financingInsight: "If financing is part of your plan, banks evaluate demand evidence on a spectrum: (1) Signed contracts/deposits - strongest, (2) Letters of intent - strong, (3) Waitlist sign-ups - moderate, (4) Survey interest - helpful but not decisive, (5) General belief in demand - not enough. Building toward levels 1-2 strengthens any application.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "narrative",
    dismissible: true,
    autoExpandFor: ["basics"],
    order: 20,
    highFriction: true,
    priority: "high",
  },
  narrative_retention: {
    id: "narrative_retention",
    title: "Articulating Your Retention Plan",
    body: {
      whatThisMeans: "This section describes how you'll keep families year over year. Acquiring a new student costs 3-5x more than retaining one, so retention is a key financial lever.",
      whyItMatters: "Strong plans show that you've thought about what happens after families enroll. A school that loses 30% of students each year needs to replace them just to stay flat - and recruitment costs eat into margins. Retention above 85% is what makes 5-year projections believable.",
      healthyVsRisky: "Strong: 'Our re-enrollment process begins in January with family conferences. We track family satisfaction quarterly through surveys, and our parent liaison addresses concerns within 48 hours. We target 90% retention.' Weak: 'We believe families will stay because they'll love our program.'",
      whatToDoNext: "Describe your re-enrollment timeline, family communication plan, and how you'll measure satisfaction. If you have retention data from a pilot or similar school, include it. Specific processes (surveys, conferences, parent liaisons) are more convincing than general intentions.",
    },
    extraBody: {
      workedExample: "Example - retention compounding over 5 years with 100 Year 1 students: At 90% retention, Year 2 returning = 90 (need 10 new). At 80% retention, Year 2 returning = 80 (need 20 new). By Year 5, cumulative students needing replacement: 90% retention = 41 total new students needed. 80% retention = 82 total new students needed - double the recruitment effort and cost. At $500 per-student acquisition cost, that's $20K vs $41K over 5 years just in recruitment.",
      benchmarkDetail: "Retention benchmarks: High-performing charter schools: 90-95% retention. Average charter schools: 82-88%. Schools below 80% retention face a 'treadmill effect' - constant recruitment just to maintain enrollment. Re-enrollment best practices: Begin process in January, confirm by March, fill remaining seats April-August. Schools that wait until summer to start re-enrollment consistently underperform.",
      glossaryTerms: "Retention Rate: Students who return the following year divided by prior year enrollment (excluding graduates). Attrition: The opposite of retention - students who leave. Churn Cost: The total cost of replacing a departing student (marketing, enrollment processing, onboarding). Net Promoter Score (NPS): A survey measure of parent satisfaction that predicts retention - scores above 50 correlate with >90% retention.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "narrative",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 21,
    highFriction: false,
    priority: "standard",
  },
  narrative_risk_mitigation: {
    id: "narrative_risk_mitigation",
    title: "Presenting Risk Mitigation",
    body: {
      whatThisMeans: "This section shows you've stress-tested your plan. What happens if enrollment is 20% below target? What if retention drops to 70%? What expenses can you cut without closing the school?",
      whyItMatters: "Good planning assumes something will go wrong. Founders who acknowledge risks and present specific contingencies are seen as realistic operators. Founders who claim 'everything will go as planned' are seen as inexperienced. This section can make or break reviewer confidence.",
      healthyVsRisky: "Strong: 'If Year 1 enrollment is 20% below target, we'll defer 2 non-essential hires (saving $85K) and reduce marketing spend by $10K. Our lease allows subletting one classroom. We maintain a 60-day operating reserve for cash flow gaps.' Weak: 'If enrollment is low, we'll work harder to recruit students and reduce costs.'",
      whatToDoNext: "Walk through 2-3 specific downside scenarios (low enrollment, delayed funding, unexpected costs) and describe your response for each. Name the expenses you'd cut and the dollar amounts. Show that you've identified which costs are flexible and which are locked in.",
    },
    extraBody: {
      workedExample: "Example risk mitigation table: Scenario 1 - Enrollment 20% below target (64 vs 80 students): Revenue impact -$160K. Response: Defer 2 hires (-$110K), reduce supplies budget (-$20K), negotiate rent deferral (-$30K). Net gap: $0. Scenario 2 - Grant delayed 6 months ($50K): Bridge with startup reserve ($50K available). Scenario 3 - Key staff departure mid-year: Cross-trained backup identified for each critical role, $15K emergency recruitment budget reserved.",
      financingInsight: "If financing is part of your plan, reviewers look for three things in risk planning: (1) Are the risks realistic - not minor inconveniences but genuine threats? (2) Are the responses specific - dollar amounts, named actions, timelines? (3) Is there a contingency plan - what would you do if things got really tough? Founders who can calmly discuss difficult scenarios inspire more confidence, not less.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "narrative",
    dismissible: true,
    autoExpandFor: ["basics"],
    order: 22,
    highFriction: true,
    priority: "high",
  },
  narrative_revenue_expenses: {
    id: "narrative_revenue_expenses",
    title: "Explaining Revenue & Expense Assumptions",
    body: {
      whatThisMeans: "This section explains the reasoning behind your financial numbers - why you set tuition at a specific level, why you chose your staffing ratios, and why certain expenses are higher or lower than benchmarks.",
      whyItMatters: "Reviewers don't just read the numbers - they read the logic behind them. A tuition rate of $12,000 needs context: is that below market? At market? Is there data to support families' ability to pay? Every assumption that deviates from benchmarks needs an explanation.",
      healthyVsRisky: "Strong: 'Tuition is set at $11,500, which is 15% below the average for independent schools in our zip code ($13,500). We chose this to maximize enrollment accessibility while covering per-student costs of $9,800.' Weak: 'Our tuition is competitive for the area.'",
      whatToDoNext: "For each major assumption (tuition, staffing ratio, facility cost, growth rate), provide the reasoning and any market data that supports it. If an assumption differs from typical benchmarks, explain why. Concrete numbers and comparisons are always stronger than qualitative statements.",
    },
    extraBody: {
      workedExample: "Example assumption narrative: 'Staffing: We budget 8.5 FTE in Year 1 for 80 students (9.4:1 ratio). This includes 5 teachers (16:1 student-teacher ratio), 1 SpEd coordinator, 1 operations manager, 1 Head of School, and a 0.5 FTE finance consultant. Year 2 adds 2 teachers as enrollment reaches 110, maintaining the 16:1 ratio. Average teacher salary of $48,000 is benchmarked to the district median ($52,000) with a 7.7% discount to reflect our startup stage, offset by our PD investment and culture advantages.'",
      benchmarkDetail: "Assumption justification benchmarks: Tuition should reference 2-3 comparable schools with specific dollar amounts. Staffing ratios should cite state requirements or authorizer expectations. Facility costs should reference actual lease quotes or market comparables. Growth rates should be justified by documented demand, not aspirational targets. Any assumption >15% different from industry benchmarks needs explicit justification.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "narrative",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 23,
    highFriction: false,
    priority: "standard",
  },
  breakeven_analysis: {
    id: "breakeven_analysis",
    title: "Break-Even Analysis",
    body: {
      whatThisMeans: "Break-even analysis tells you exactly how many students you need to cover all your costs - the point where revenue equals expenses. Below this number, you lose money. Above it, every additional student adds to your surplus.",
      whyItMatters: "Your break-even enrollment is the most important number in your financial model after total enrollment. It tells you how much margin for error you have. If your projected enrollment is barely above break-even, any shortfall puts the school in the red. Any serious reviewer will calculate this number, even if you don't present it.",
      healthyVsRisky: "Healthy: break-even enrollment is 70-80% of projected enrollment, giving you a 20-30% cushion. Risky: break-even is 90%+ of projected enrollment - a small miss puts you underwater. Critical: break-even exceeds projected enrollment - the model doesn't work at any realistic enrollment level.",
      whatToDoNext: "Calculate your break-even point: Total Fixed Costs ÷ (Revenue per Student - Variable Cost per Student). Compare this to your projected enrollment. If break-even is above 85% of projected enrollment, look for ways to reduce fixed costs or increase per-student revenue.",
    },
    extraBody: {
      workedExample: "Example: Fixed costs = $600K (admin salaries $280K, rent $120K, insurance $8K, debt service $48K, other fixed $144K). Revenue per student = $10,000. Variable cost per student = $2,000 (supplies, food, per-student tech). Contribution margin = $10,000 - $2,000 = $8,000. Break-even = $600K ÷ $8,000 = 75 students. If you project 100 students, your cushion is 25 students (25%). At 80 students, surplus = 5 × $8,000 = $40K. At 70 students (below break-even), deficit = 5 × $8,000 = -$40K.",
      benchmarkDetail: "Break-even benchmarks: Most viable school models break even at 65-80% of target capacity. Schools that can't break even below 90% of capacity face high risk. The national average break-even for new charter schools is approximately 72% of Year 1 target enrollment. Schools with high fixed costs (expensive leases, large admin teams) have higher break-even points.",
      glossaryTerms: "Break-Even Enrollment: The exact number of students needed for revenue to equal expenses. Contribution Margin: Revenue per student minus variable cost per student - what each student contributes to covering fixed costs. Margin of Safety: The difference between projected enrollment and break-even enrollment, expressed as a percentage. Operating Leverage: Schools with high fixed costs and low variable costs have high operating leverage - they lose money quickly below break-even but profit grows quickly above it.",
      financingInsight: "If financing is part of your plan, banks will independently calculate your break-even enrollment. The strongest models show break-even at or below 70% of projected enrollment - that cushion gives everyone confidence that the school can weather a slow start.",
    },
    audienceLevel: ["extra"],
    relatedSection: "review",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 24,
    highFriction: true,
    priority: "high",
  },
  dscr_explained: {
    id: "dscr_explained",
    title: "Debt Service Coverage Ratio (DSCR) Explained",
    body: {
      whatThisMeans: "DSCR measures whether your school generates enough cash flow to cover its loan payments. It's calculated as: Net Operating Income ÷ Annual Debt Service. A DSCR of 1.5x means you earn 50% more than you owe in loan payments.",
      whyItMatters: "If you're taking on any debt - facility loans, equipment financing, working capital lines - DSCR is the metric banks use to decide whether to approve your loan and at what rate. It's the financial equivalent of 'can you afford this?'",
      healthyVsRisky: "Above 1.25x: Strong - comfortable position. 1.15x-1.25x: Adequate but tight - may require additional security. 1.0x-1.15x: Marginal - most banks will decline or require personal guarantees. Below 1.0x: The school cannot cover its debt from operations.",
      whatToDoNext: "If your model shows debt, check the DSCR on your Review page. If it's below 1.2x, consider: reducing loan amount, extending loan term (lower annual payments), increasing revenue, or cutting non-essential expenses to improve cash flow.",
    },
    extraBody: {
      workedExample: "Example: Year 1 revenue $1.2M, total expenses (excluding debt) $1.05M. Net Operating Income = $150K. Annual debt service on a $600K loan at 7% over 10 years = $85K. DSCR = $150K ÷ $85K = 1.76x - healthy. Now stress-test: if enrollment drops 15%, revenue falls to $1.02M, NOI drops to $-30K. DSCR = -0.35x - the school can't make loan payments. This shows why cushion matters: your base case looks fine, but a modest enrollment miss makes debt unsustainable.",
      benchmarkDetail: "DSCR benchmarks by financing type: Traditional banks typically require 1.25x-1.50x. CDFIs (community development financial institutions) may accept 1.10x-1.20x for mission-aligned projects. SBA loans require 1.15x-1.25x. Bond financing (for larger projects) typically requires 1.30x-1.50x. DSCR is evaluated both on a trailing 12-month basis and on projected figures.",
      glossaryTerms: "Net Operating Income (NOI): Total revenue minus total operating expenses, before debt service payments. Debt Service: Total annual loan payments including both principal and interest. Coverage Ratio: NOI divided by debt service - how many times over you can cover your loan payments. Debt Covenant: A condition in your loan requiring you to maintain a minimum DSCR (typically 1.15x-1.25x) - violating it can trigger default.",
      financingInsight: "If you're applying for financing, DSCR drives your loan terms. Banks typically evaluate it three ways: (1) using your projections, (2) using conservative stress-tested numbers, and (3) using peer school benchmarks. Improving DSCR by even 0.1x can meaningfully improve the terms you're offered.",
    },
    audienceLevel: ["extra"],
    relatedSection: "review",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 25,
    highFriction: true,
    priority: "high",
  },
  assumptions_cola: {
    id: "assumptions_cola",
    title: "COLA (Cost of Living Adjustment)",
    body: {
      whatThisMeans: "COLA is the annual percentage increase applied to every staff salary in your model. It keeps compensation competitive as the cost of living rises - think of it as the automatic raise your team gets each year.",
      whyItMatters: "If salaries don't keep pace with the cost of living, you'll lose good teachers to higher-paying schools. But if you set COLA too high, payroll costs can outpace revenue growth. Finding the right balance matters for both retention and sustainability.",
      healthyVsRisky: "2–3% is typical for most schools and matches national cost-of-living trends. Below 2% may make it harder to retain staff. Above 4% is aggressive and can squeeze your budget in later years - worth watching closely.",
      whatToDoNext: "The default of 3% is a solid starting point for most schools. If you're in a high-cost area (SF, NYC, DC), you might consider 3.5–4%. In lower-cost areas, 2–2.5% may be appropriate. You can always adjust later.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "assumptions",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 30,
    highFriction: false,
    priority: "standard",
  },
  assumptions_benefits_rate: {
    id: "assumptions_benefits_rate",
    title: "Benefits Rate",
    body: {
      whatThisMeans: "The benefits rate is the percentage of each employee's salary that goes toward benefits - health insurance, retirement contributions, disability, and similar. A 25% rate on a $50,000 salary means $12,500 in benefits costs on top of the salary.",
      whyItMatters: "Benefits are a major hidden cost. Many first-time founders budget salaries but underestimate benefits, which can add 20–35% to every payroll dollar. Getting this rate realistic is essential for an accurate staffing budget.",
      healthyVsRisky: "20–25% is common for schools offering a basic benefits package. 25–30% is typical when including strong health coverage and retirement match. Above 30% is generous but can put pressure on smaller budgets. Below 20% may signal limited benefits that make recruiting harder.",
      whatToDoNext: "If you're not sure, 25% is a safe default. If you've already quoted health insurance plans, you can calculate a more precise rate. Individual roles can override this default on the Staffing step.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "assumptions",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 31,
    highFriction: false,
    priority: "standard",
  },
  assumptions_collection_rate: {
    id: "assumptions_collection_rate",
    title: "Collection Rate",
    body: {
      whatThisMeans: "The collection rate is the percentage of billed tuition your school actually receives. A 95% collection rate on $1M in billed tuition means you'll collect $950,000 - the other $50,000 represents late payments, financial hardship, and uncollectible accounts.",
      whyItMatters: "Planning for 100% collection is one of the most common mistakes in school financial models. Real-world collection rates for invoiced families typically range from 92–98%. Even a small gap can mean tens of thousands in missing revenue.",
      healthyVsRisky: "95–98% is realistic for schools with autopay. 92–96% is typical for invoiced families. Below 90% suggests significant collection challenges worth addressing. 100% is only realistic if all families are on autopay with no exceptions.",
      whatToDoNext: "If you're using autopay for most families, 98–100% is reasonable. If you're invoicing, 93–95% is a safer assumption. You can set this per revenue row on the Revenue step if different programs have different collection profiles.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "assumptions",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 32,
    highFriction: false,
    priority: "standard",
  },
  assumptions_general_inflation: {
    id: "assumptions_general_inflation",
    title: "General Cost Inflation",
    body: {
      whatThisMeans: "General cost inflation is the annual percentage increase applied to most non-salary expenses - supplies, insurance, utilities, professional services, and similar operating costs. It reflects the reality that things get more expensive over time.",
      whyItMatters: "Without inflation built in, your Year 5 projections will look artificially strong because expenses stay flat while (hopefully) revenue grows. Realistic inflation keeps your model honest and prevents surprises in later years.",
      healthyVsRisky: "2–3% matches long-term US inflation averages and is appropriate for most schools. 0% means you're assuming costs never rise - optimistic but unrealistic for a 5-year plan. Above 4% may overstate cost growth unless you're in a period of high inflation.",
      whatToDoNext: "The default of 2% is conservative and appropriate for most situations. If you have specific vendor contracts with locked pricing, you might set this lower. Leave it as-is unless you have a reason to change it.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "assumptions",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 33,
    highFriction: false,
    priority: "standard",
  },
  revenue_timing: {
    id: "revenue_timing",
    title: "Revenue Timing & Cash Flow",
    body: {
      whatThisMeans: "Revenue timing is when money actually arrives in your bank account - not when you earn it on paper. A school can be 'profitable' on an annual basis but still run out of cash if payments arrive late.",
      whyItMatters: "The gap between when you owe bills and when revenue arrives is where most first-year schools feel the squeeze. Understanding payment timing helps you plan for the lean months and avoid surprises.",
      healthyVsRisky: "Healthy: Revenue arrives monthly or quarterly on predictable schedules. Worth watching: Large portions of revenue come from reimbursement-based programs with 45-60 day lag. The risk grows when multiple delayed sources stack up in the same months.",
      whatToDoNext: "For each revenue source, think about when the money actually hits your account. Set the timing controls to match reality. If most of your revenue arrives after September, make sure you have enough cash to cover July and August expenses.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "revenue",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 34,
    highFriction: false,
    priority: "standard",
  },
  staffing_ramp: {
    id: "staffing_ramp",
    title: "Staffing Ramp & Ratios",
    body: {
      whatThisMeans: "Staffing ramp is how your team grows as enrollment increases. You can set each role as a fixed number of people or let it scale automatically with a student-to-staff ratio.",
      whyItMatters: "Personnel is typically 55-65% of a school's budget. Getting staffing right means hiring the people you need when you need them - not too early (which burns cash) and not too late (which hurts quality).",
      healthyVsRisky: "Healthy: Ratio-driven roles for teachers and aides, fixed roles for leadership and operations. Worth watching: Hiring your full Year 5 team in Year 1 when you only have 60 students. A good plan phases in staff as enrollment grows.",
      whatToDoNext: "For teaching roles, try 'Student Ratio' mode - it automatically adjusts headcount as enrollment grows. For leadership and admin roles, 'Fixed FTE' makes more sense since those don't scale linearly with students.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "staffing",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 35,
    highFriction: false,
    priority: "standard",
  },
  expense_categories: {
    id: "expense_categories",
    title: "Expense Categories & Completeness",
    body: {
      whatThisMeans: "Your operating expenses cover everything beyond personnel - facility costs, technology, curriculum, insurance, and professional services. These are grouped into categories to help you think through each area systematically.",
      whyItMatters: "Underestimating expenses is the most common mistake in first-year school budgets. It's better to overestimate slightly and come in under budget than to be surprised by costs you forgot to plan for.",
      healthyVsRisky: "Healthy: Every category has been reviewed and adjusted for your school's reality. Worth watching: Leaving default amounts without checking them. Common gaps: insurance, legal fees, marketing, professional development, and technology refresh costs.",
      whatToDoNext: "Walk through each expense category and ask: 'Does this feel right for my school?' Don't worry about being exact - a reasonable estimate is far better than a gap. You can always refine these numbers later.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "expenses",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 36,
    highFriction: false,
    priority: "standard",
  },
  working_capital: {
    id: "working_capital",
    title: "Working Capital Management",
    body: {
      whatThisMeans: "Working capital is the cash you need to cover day-to-day operations between when expenses are due and when revenue arrives. It's the bridge that keeps your school running during timing gaps in your cash flow.",
      whyItMatters: "Even profitable schools can fail if they run out of cash. Working capital shortfalls are the #1 reason new schools face financial crises in their first two years. You might have a great annual budget, but if your cash runs out in September because tuition hasn't been collected yet, you can't make payroll.",
      healthyVsRisky: "Healthy: 60-90 days of operating expenses available as working capital. Adequate: 30-60 days. Risky: less than 30 days. Critical: relying on next month's revenue to pay this month's bills. Schools in the 'critical' zone are one delayed payment away from a crisis.",
      whatToDoNext: "Calculate your monthly operating expenses (total annual expenses ÷ 12). Multiply by 2-3 to get your minimum working capital target. If your starting cash is below this amount, plan for how you'll bridge the gap - startup grants, a line of credit, or delayed spending.",
    },
    extraBody: {
      workedExample: "Example: Monthly expenses = $75K. Working capital target = 2.5 months = $187.5K. You start with $120K cash. In July (before school starts), you pay $75K in expenses with $0 revenue. Cash drops to $45K. August: another $75K in expenses, $0 revenue. Cash = -$30K - you're out of money before a single student arrives. You needed $187.5K to safely bridge this gap. Solution: secure a $75K line of credit or $75K startup grant to supplement your $120K starting cash.",
      benchmarkDetail: "Working capital benchmarks: New schools should target 60-90 days of operating expenses before doors open. The most cash-intensive period is typically June-September (staff hired, facility prepared, no revenue yet). Working capital sources: startup grants (most common), founder investment, pre-opening fundraising, lines of credit ($25K-$100K from CDFIs). Cost of a line of credit: 6-10% interest on drawn amounts, plus 0.25-0.50% annual fee on undrawn balance.",
      glossaryTerms: "Working Capital: Current assets minus current liabilities - practically, the cash available to cover short-term obligations. Cash Conversion Cycle: The time between paying expenses and collecting revenue - for schools, this can be 30-90 days. Line of Credit: A pre-approved borrowing facility that lets you draw cash when needed and repay when revenue arrives - different from a term loan because you only pay interest on what you use. Days Cash on Hand: Your cash balance divided by daily operating expenses - the most direct measure of working capital adequacy.",
      financingInsight: "If financing is part of your plan, banks view working capital as a survival metric. Starting with less than 45 days of operating expenses in cash is considered risky regardless of how strong your annual budget looks. Your minimum cash position across the entire projection matters - if it goes negative at any point, the model needs work even if the annual budget balances.",
    },
    audienceLevel: ["extra"],
    relatedSection: "review",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 26,
    highFriction: true,
    priority: "high",
  },
  accounting_basis: {
    id: "accounting_basis",
    title: "Accounting Basis",
    body: {
      whatThisMeans: "Your accounting basis describes when you record revenue and expenses. Cash basis means you record transactions when money actually changes hands. Accrual basis means you record them when they're earned or incurred, regardless of when payment happens.",
      whyItMatters: "We build every model on an accrual basis - it gives the most complete and accurate picture of your school's financial health. Even if you currently track your books on a cash basis (which is perfectly fine for day-to-day operations), your 5-year projections need to show when revenue is earned and expenses are committed, not just when checks clear.",
      healthyVsRisky: "There's no wrong answer here. Many small schools start on cash basis because it's simpler - that's completely normal. What matters is that your financial model projects on an accrual basis so that anyone reviewing it (a board, an authorizer, a lender) sees a complete picture. Your day-to-day bookkeeping method is a separate decision.",
      whatToDoNext: "Select whichever option describes how you currently keep your books. If you're not sure, choose 'Not sure yet' - we'll note it and your model will work exactly the same either way. All projections use accrual accounting regardless of your selection.",
    },
    extraBody: {
      workedExample: "Example: Your school bills $120K in tuition for September, but only collects $100K by September 30th (the rest arrives in October). Cash basis records $100K revenue in September and $20K in October. Accrual basis records $120K in September because that's when it was earned. The annual total is the same - $120K - but accrual gives a more accurate monthly picture of your financial position.",
      glossaryTerms: "Cash Basis: Revenue recorded when received, expenses recorded when paid. Simplest method, common for small organizations. Accrual Basis: Revenue recorded when earned, expenses recorded when incurred. Required for GAAP-compliant financial statements and most grant reporting. Modified Cash Basis: A hybrid approach some schools use - cash basis with certain accrual adjustments. GAAP: Generally Accepted Accounting Principles - the standard framework for financial reporting in the U.S.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "school_profile",
    dismissible: true,
    autoExpandFor: ["basics"],
    order: 36,
    highFriction: false,
    priority: "standard",
  },
  reading_your_analysis: {
    id: "reading_your_analysis",
    title: "How to Read Your Analysis",
    body: {
      whatThisMeans: "This page summarizes everything you've entered into your financial model. It translates your numbers into key metrics, charts, and a plain-English health check so you can see how your school looks on paper before you share it with anyone else.",
      whyItMatters: "A budget spreadsheet tells you what the numbers are. This analysis tells you what the numbers mean. It's the difference between 'staffing costs are $450K' and 'staffing is 65% of revenue - that's typical for a school your size.' Understanding these patterns helps you spot strengths and weaknesses before a board member, authorizer, or lender does.",
      healthyVsRisky: "Healthy: You understand why each metric is green, yellow, or red, and you've made conscious choices about any watch items. Worth watching: You're not sure what a metric means or why it's flagged. Common misread: Assuming all 'watch' items are problems - some are perfectly normal trade-offs for your school model.",
      whatToDoNext: "Start with 'The bottom line' summary at the top. Then scan the key metrics - focus on any yellow or red items first. Click 'How is this calculated?' on any metric you don't understand. If something looks off, use the 'Jump to step' buttons to go back and adjust your inputs.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "consultant",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 37,
    highFriction: false,
    priority: "standard",
  },
  writing_your_narrative: {
    id: "writing_your_narrative",
    title: "Writing Your Budget Narrative",
    body: {
      whatThisMeans: "Your budget narrative is the story behind the numbers. It explains why you made the financial choices you did, how you plan to hit your targets, and what you'll do if things don't go as planned. Think of it as the 'why' that complements the 'what' in your spreadsheets.",
      whyItMatters: "Numbers alone don't tell a complete story. A board member reviewing your budget will want to know: 'Why did you choose this tuition level?' 'How will you actually get 120 students enrolled?' 'What happens if you fall short?' Your narrative answers these questions and builds confidence that you've thought through the plan, not just the math.",
      healthyVsRisky: "Healthy: Each section is written in your own words, addresses the specific question, and gives concrete details (names of neighborhoods, partner organizations, specific marketing tactics). Worth watching: Generic answers that could apply to any school. Common gap: Skipping the risk mitigation section - that's actually the most important one for building credibility.",
      whatToDoNext: "Start with the three priority sections (marked in amber): enrollment strategy, retention plan, and risk mitigation. Write naturally, as if you're explaining your plan to a supportive mentor. Don't worry about perfect prose - clarity and specificity matter more than polish.",
    },
    audienceLevel: ["basics", "extra"],
    relatedSection: "narrative",
    dismissible: true,
    autoExpandFor: ["extra"],
    order: 38,
    highFriction: false,
    priority: "standard",
  },
};

export function getExplainersForSection(section: string, level: GuidanceLevel): Explainer[] {
  return Object.values(EXPLAINERS)
    .filter((e) => e.relatedSection === section && e.audienceLevel.includes(level))
    .sort((a, b) => a.order - b.order);
}

export function getExplainerById(id: string): Explainer | undefined {
  return EXPLAINERS[id];
}

export function shouldAutoExpand(level: GuidanceLevel, explainer: Explainer): boolean {
  if (level === "advanced") return false;
  return explainer.autoExpandFor.includes(level);
}
