ALTER TABLE users ADD COLUMN IF NOT EXISTS school_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_role TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS planning_stage TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mailing_list_opt_in BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS guidance_level VARCHAR(20);

ALTER TABLE feedback ADD COLUMN IF NOT EXISTS score INTEGER;
