export const DEFAULT_BENEFITS_RATE = 25;
export const DEFAULT_PAYROLL_TAX_RATE = 8;
export const DEFAULT_COLA_PCT = 3;
export const DEFAULT_GENERAL_INFLATION_PCT = 3;
export const DEFAULT_RENT_ESCALATION_PCT = 3;
export const DEFAULT_TUITION_ESCALATION_PCT = 3;
export const DEFAULT_RETENTION_RATE = 85;

export const LOADED_COST_MULTIPLIER = 1 + (DEFAULT_BENEFITS_RATE + DEFAULT_PAYROLL_TAX_RATE) / 100;

export const YEAR_COUNT = 5;

export const BENCHMARK_DSCR_GREEN = 1.25;
export const BENCHMARK_DSCR_AMBER = 1.15;
