import { Layout } from "@/components/layout/Layout";
import { SEOHead } from "@/components/SEOHead";

export function TermsPage() {
  return (
    <Layout>
      <SEOHead
        title="Terms of Service"
        description="Terms of Service for SchoolStack Budget, a financial modeling tool for school founders operated by Building Hope Impact Fund."
        path="/terms"
        noIndex
      />
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <h1 className="font-display text-3xl sm:text-4xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: March 15, 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-foreground/85 leading-relaxed">
          <section>
            <h2 className="font-display text-xl font-bold text-foreground">1. Acceptance of Terms</h2>
            <p>
              By accessing or using SchoolStack Budget ("the Service"), operated by Building Hope Impact Fund ("we," "us," or "our"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">2. Description of Service</h2>
            <p>
              SchoolStack Budget is a financial modeling tool that helps school founders create multi-year financial projections. The Service provides guided data entry, automated calculations, consultant-grade analysis, and exportable workbooks. The Service is provided for informational and planning purposes only.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">3. No Financial Advice</h2>
            <p>
              The Service does not provide financial, legal, tax, investment, or accounting advice. All projections, analyses, benchmarks, stress tests, recommendations, and outputs generated by the Service are estimates based on the assumptions you provide. They are not guarantees of future performance and should not be relied upon as the sole basis for any financial decision.
            </p>
            <p>
              You should consult with qualified financial, legal, and tax professionals before making any decisions based on information provided by the Service. We expressly disclaim any responsibility for decisions made based on outputs from the Service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">4. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate, current, and complete information during registration. You must notify us immediately of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">5. User Data and Content</h2>
            <p>
              You retain ownership of the data you input into the Service. By using the Service, you grant us a limited license to store, process, and display your data solely for the purpose of providing the Service to you. We will not sell your data to third parties.
            </p>
            <p>
              You are solely responsible for the accuracy, completeness, and legality of the data you provide. We are not responsible for verifying the accuracy of your inputs or the resulting projections.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">6. Limitation of Liability and Indemnification</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT.
            </p>
            <p>
              IN NO EVENT SHALL BUILDING HOPE IMPACT FUND, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p>
              OUR TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED DOLLARS ($100), WHICHEVER IS GREATER.
            </p>
            <p>
              You agree to indemnify, defend, and hold harmless Building Hope Impact Fund and its officers, directors, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any rights of a third party; (d) any decisions made or actions taken based on outputs from the Service; or (e) any financial models, projections, or documents you create using the Service and present to third parties, including lenders, investors, or regulatory bodies.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">7. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service for any unlawful purpose</li>
              <li>Misrepresent the outputs of the Service as certified financial statements or audited reports</li>
              <li>Attempt to reverse-engineer, decompile, or disassemble the Service</li>
              <li>Use automated systems to access the Service in a manner that sends more requests than a human could reasonably produce</li>
              <li>Share your account credentials with others</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">8. Intellectual Property</h2>
            <p>
              The Service, including its design, features, content, and code, is the property of Building Hope Impact Fund and is protected by applicable intellectual property laws. You may not copy, modify, distribute, or create derivative works of the Service without our prior written consent.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">9. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service will immediately cease. You may export your data before termination by using the export features provided within the Service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will provide notice of material changes by posting the updated Terms on the Service. Your continued use of the Service after such changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law principles. Any disputes arising under these Terms shall be resolved in the state or federal courts located in Delaware.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-foreground">12. Contact</h2>
            <p>
              If you have questions about these Terms, please contact us at{" "}
              <a href="mailto:admin@schoolstack.ai" className="text-primary hover:underline font-semibold">admin@schoolstack.ai</a>.
            </p>
          </section>
        </div>
      </div>
    </Layout>
  );
}
