export const microschoolStartup = {
  schoolProfile: {
    schoolName: "Bright Horizons Microschool",
    state: "AZ",
    schoolType: "microschool",
    entityType: "llc_single",
    ein: "88-1234567",
    schoolStage: "new_school",
    fundingProfile: "tuition_based",
    openingYear: 2026,
    currentStudents: 0,
    maxCapacity: 25,
    fiscalYearStartMonth: 7,
    isPartialFirstYear: true,
    year1OperatingMonths: 10,
    locationSecured: true,
    facilityStreet: "123 Main St",
    facilityCity: "Scottsdale",
    facilityState: "AZ",
    facilityZip: "85251",
    ownershipType: "rent",
    monthlyRent: 2500,
    annualRentEscalation: 3,
    debtIncluded: false,
  },
  enrollment: { year1: 12, year2: 18, year3: 22, year4: 25, year5: 25 },
  revenue: {
    tuitionPerStudent: 12000,
    annualTuitionIncrease: 3,
    annualFundraising: 5000,
    annualDonations: 2000,
  },
  revenueRows: [
    { id: "r1", category: "tuition_and_fees", lineItem: "Tuition", enabled: true, driverType: "per_student", amounts: [12000, 12360, 12731, 13113, 13506], billingMonths: 10 },
    { id: "r2", category: "tuition_and_fees", lineItem: "Registration Fee", enabled: true, driverType: "per_student", amounts: [250, 250, 250, 250, 250], billingMonths: 12 },
    { id: "r3", category: "school_choice", lineItem: "AZ ESA Funds", enabled: true, driverType: "per_student", amounts: [7000, 7210, 7426, 7649, 7878], billingMonths: 12 },
    { id: "r4", category: "philanthropy", lineItem: "Annual Fundraising", enabled: true, driverType: "annual_fixed", amounts: [5000, 6000, 7000, 8000, 9000] },
    { id: "r5", category: "tuition_offsets", lineItem: "Scholarship Discount", enabled: true, driverType: "percent_of_base", amounts: [10, 10, 10, 10, 10], percentBase: "r1" },
  ],
  staffing: {
    studentsPerTeacher: 8,
    teacherSalary: 45000,
    founderSalary: 55000,
    benefitsRate: 20,
  },
  staffingRows: [
    { id: "s1", roleName: "Founder / Head of School", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 55000, benefitsEligible: true, benefitsRate: 20, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s2", roleName: "Lead Teacher", functionCategory: "instructional", employmentType: "full_time", fte: 1, annualizedRate: 45000, benefitsEligible: true, benefitsRate: 20, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s3", roleName: "Teaching Assistant", functionCategory: "instructional", employmentType: "part_time", fte: 0.5, annualizedRate: 28000, benefitsEligible: false, benefitsRate: 0, payrollTaxRate: 7.65, payrollLike: false },
  ],
  facilities: {
    monthlyRent: 2500,
    annualRentIncrease: 3,
    annualUtilities: 3600,
    annualInsurance: 2400,
    curriculumCostPerStudent: 500,
    techCostPerStudent: 300,
    annualMarketing: 3000,
    annualSalaryIncrease: 3,
    generalCostInflation: 2.5,
  },
  expenseRows: [
    { id: "e1", category: "occupancy_facility", lineItem: "Rent", enabled: true, driverType: "monthly", amounts: [2500, 2575, 2652, 2732, 2814], escalationRate: 3 },
    { id: "e2", category: "occupancy_facility", lineItem: "Utilities", enabled: true, driverType: "monthly", amounts: [300, 308, 316, 324, 332] },
    { id: "e3", category: "occupancy_facility", lineItem: "Insurance", enabled: true, driverType: "annual_fixed", amounts: [2400, 2460, 2522, 2585, 2650] },
    { id: "e4", category: "instructional_program", lineItem: "Curriculum & Materials", enabled: true, driverType: "per_student", amounts: [500, 515, 530, 546, 562] },
    { id: "e5", category: "technology", lineItem: "Technology", enabled: true, driverType: "per_student", amounts: [300, 309, 318, 328, 338] },
    { id: "e6", category: "administrative_general", lineItem: "Marketing", enabled: true, driverType: "annual_fixed", amounts: [3000, 3075, 3152, 3231, 3312] },
  ],
  capitalAndDebtRows: [
    { id: "cd1", lineItem: "Equipment Loan", enabled: true, driverType: "annual_fixed", amounts: [0, 0, 0, 0, 0], isLoan: true, loanPrincipal: 30000, loanRate: 6, loanTermYears: 5, purpose: "startup" },
  ],
  openingBalances: { cash: 15000, accountsReceivable: 0, fixedAssets: 5000, otherAssets: 0, accountsPayable: 0, currentDebtPortion: 0, longTermDebt: 0 },
  sourcesAndUses: {
    sources: [
      { lineItem: "Owner Equity", amount: 20000, category: "equity" },
    ],
    uses: [
      { lineItem: "Startup Costs", amount: 15000, category: "startup" },
      { lineItem: "Working Capital Reserve", amount: 5000, category: "reserves" },
    ],
  },
  scenarios: [
    { name: "Base Case", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Low Enrollment", enrollmentAdjustment: -20, tuitionAdjustment: 0, expenseAdjustment: 0 },
  ],
  covenantThresholds: { minDSCR: 1.2, minDaysCashOnHand: 45, minMonthsRunway: 3 },
};

export const homeschoolCoopMixed = {
  schoolProfile: {
    schoolName: "Liberty Learning Co-Op",
    state: "AZ",
    schoolType: "homeschool_coop",
    entityType: "llc_single",
    ein: "86-5551234",
    schoolStage: "new_school",
    fundingProfile: "hybrid_mixed",
    openingYear: 2026,
    currentStudents: 0,
    maxCapacity: 40,
    fiscalYearStartMonth: 7,
    isPartialFirstYear: true,
    year1OperatingMonths: 10,
    locationSecured: true,
    facilityStreet: "789 Desert Way",
    facilityCity: "Mesa",
    facilityState: "AZ",
    facilityZip: "85201",
    ownershipType: "rent",
    monthlyRent: 1800,
    annualRentEscalation: 3,
    debtIncluded: false,
    spedCount: [3, 4, 5, 6, 6],
    ellCount: [2, 3, 4, 5, 5],
    ecoDisCount: [5, 7, 9, 10, 12],
    enrollmentGrowthRate: 15,
    stateFundingMethodology: "other",
  },
  enrollment: { year1: 15, year2: 22, year3: 30, year4: 36, year5: 40 },
  revenue: {
    tuitionPerStudent: 6000,
    annualTuitionIncrease: 3,
    annualFundraising: 3000,
    annualDonations: 1500,
  },
  revenueRows: [
    { id: "r1", category: "tuition_and_fees", lineItem: "Co-Op Tuition", enabled: true, driverType: "per_student", amounts: [6000, 6180, 6365, 6556, 6753], billingMonths: 10 },
    { id: "r2", category: "tuition_and_fees", lineItem: "Materials Fee", enabled: true, driverType: "per_student", amounts: [200, 200, 200, 200, 200], billingMonths: 12, escalationRate: 0, escalationRateOverridden: true },
    { id: "esa_revenue", category: "school_choice", lineItem: "ESA Revenue", enabled: true, driverType: "per_student", amounts: [7000, 7210, 7426, 7649, 7878], billingMonths: 12 },
    { id: "refundable_tax_credit", category: "school_choice", lineItem: "Refundable Tax Credit", enabled: false, driverType: "per_student", amounts: [0, 0, 0, 0, 0], billingMonths: 12 },
    { id: "r5", category: "philanthropy", lineItem: "Annual Fundraising", enabled: true, driverType: "annual_fixed", amounts: [3000, 4000, 5000, 5000, 5000] },
  ],
  staffingRows: [
    { id: "s1", roleName: "Director / Lead Educator", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 48000, benefitsEligible: true, benefitsRate: 20, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s2", roleName: "Assistant Educator", functionCategory: "instructional", employmentType: "part_time", fte: 0.5, annualizedRate: 30000, benefitsEligible: false, benefitsRate: 0, payrollTaxRate: 7.65, payrollLike: false },
  ],
  facilities: {
    monthlyRent: 1800,
    annualRentIncrease: 3,
    annualUtilities: 2400,
    annualInsurance: 1800,
    curriculumCostPerStudent: 400,
    techCostPerStudent: 250,
    annualMarketing: 2000,
    annualSalaryIncrease: 3,
    generalCostInflation: 2.5,
  },
  expenseRows: [
    { id: "e1", category: "occupancy_facility", lineItem: "Rent", enabled: true, driverType: "monthly", amounts: [1800, 1854, 1910, 1967, 2026], escalationRate: 3 },
    { id: "e2", category: "occupancy_facility", lineItem: "Utilities", enabled: true, driverType: "monthly", amounts: [200, 205, 210, 215, 221] },
    { id: "e3", category: "occupancy_facility", lineItem: "Insurance", enabled: true, driverType: "annual_fixed", amounts: [1800, 1845, 1891, 1938, 1987] },
    { id: "e_static", category: "administrative_general", lineItem: "Compliance Contract", enabled: true, driverType: "annual_fixed", amounts: [4500, 4500, 4500, 4500, 4500], escalationRate: 0, escalationRateOverridden: true },
    { id: "e4", category: "instructional_program", lineItem: "Curriculum & Materials", enabled: true, driverType: "per_student", amounts: [400, 412, 424, 437, 450] },
    { id: "e5", category: "technology", lineItem: "Technology", enabled: true, driverType: "per_student", amounts: [250, 258, 265, 273, 281] },
  ],
  capitalAndDebtRows: [],
  openingBalances: { cash: 10000, accountsReceivable: 0, fixedAssets: 2000, otherAssets: 0, accountsPayable: 0, currentDebtPortion: 0, longTermDebt: 0 },
  sourcesAndUses: {
    sources: [{ lineItem: "Owner Savings", amount: 12000, category: "equity" }],
    uses: [{ lineItem: "Startup Costs", amount: 12000, category: "startup" }],
  },
  scenarios: [
    { name: "Base Case", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Low ESA Utilization", enrollmentAdjustment: -25, tuitionAdjustment: 0, expenseAdjustment: 0 },
  ],
  covenantThresholds: { minDSCR: 1.0, minDaysCashOnHand: 30, minMonthsRunway: 2 },
};

export const privateSchoolWithESA = {
  schoolProfile: {
    schoolName: "Heritage Academy",
    state: "FL",
    schoolType: "private_school",
    entityType: "nonprofit_501c3",
    ein: "59-9876543",
    schoolStage: "operating_school",
    fundingProfile: "hybrid_mixed",
    openingYear: 2023,
    currentStudents: 85,
    maxCapacity: 200,
    fiscalYearStartMonth: 7,
    isPartialFirstYear: false,
    year1OperatingMonths: 12,
    locationSecured: true,
    facilityStreet: "456 Oak Ave",
    facilityCity: "Tampa",
    facilityState: "FL",
    facilityZip: "33602",
    ownershipType: "rent",
    monthlyRent: 8500,
    annualRentEscalation: 3,
    debtIncluded: true,
    lendingLabIntent: "plan_to_apply",
  },
  enrollment: { year1: 100, year2: 130, year3: 160, year4: 185, year5: 200 },
  revenue: {
    tuitionPerStudent: 10500,
    esaRevenuePerStudent: 8700,
    annualTuitionIncrease: 3,
    scholarshipRate: 10,
    annualFundraising: 25000,
    annualDonations: 15000,
    foundationGrants: 50000,
  },
  revenueRows: [
    { id: "r1", category: "tuition_and_fees", lineItem: "Tuition", enabled: true, driverType: "per_student", amounts: [10500, 10815, 11140, 11474, 11818], billingMonths: 10, collectionMethod: "autopay", collectionRate: 95 },
    { id: "r2", category: "tuition_and_fees", lineItem: "Registration Fee", enabled: true, driverType: "per_student", amounts: [350, 350, 350, 350, 350], billingMonths: 12 },
    { id: "r3", category: "tuition_offsets", lineItem: "Scholarship Discount", enabled: true, driverType: "per_student", amounts: [-1050, -1082, -1114, -1147, -1182] },
    { id: "r4", category: "school_choice", lineItem: "FL FTC Scholarship", enabled: true, driverType: "per_student", amounts: [8700, 8961, 9230, 9507, 9792], billingMonths: 12, disbursementType: "direct" },
    { id: "r5", category: "philanthropy", lineItem: "Foundation Grant", enabled: true, driverType: "annual_fixed", amounts: [50000, 40000, 30000, 20000, 10000], grantStatus: "confirmed" },
    { id: "r6", category: "philanthropy", lineItem: "Annual Fund", enabled: true, driverType: "annual_fixed", amounts: [25000, 30000, 35000, 40000, 45000] },
    { id: "r7", category: "other_revenue", lineItem: "After-School Programs", enabled: true, driverType: "per_student", amounts: [500, 515, 530, 546, 562] },
  ],
  staffingRows: [
    { id: "s1", roleName: "Head of School", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 95000, benefitsEligible: true, benefitsRate: 25, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s2", roleName: "Assistant Principal", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 75000, benefitsEligible: true, benefitsRate: 25, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s3", roleName: "Teachers", functionCategory: "instructional", employmentType: "full_time", fte: 6, annualizedRate: 48000, benefitsEligible: true, benefitsRate: 25, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s4", roleName: "Paraprofessionals", functionCategory: "instructional", employmentType: "full_time", fte: 3, annualizedRate: 32000, benefitsEligible: true, benefitsRate: 20, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s5", roleName: "Office Manager", functionCategory: "administrative", employmentType: "full_time", fte: 1, annualizedRate: 42000, benefitsEligible: true, benefitsRate: 25, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s6", roleName: "School Counselor", functionCategory: "student_support", employmentType: "full_time", fte: 1, annualizedRate: 52000, benefitsEligible: true, benefitsRate: 25, payrollTaxRate: 7.65, payrollLike: false },
  ],
  expenseRows: [
    { id: "e1", category: "occupancy_facility", lineItem: "Rent", enabled: true, driverType: "monthly", amounts: [8500, 8755, 9018, 9289, 9567], escalationRate: 3 },
    { id: "e2", category: "occupancy_facility", lineItem: "Utilities", enabled: true, driverType: "monthly", amounts: [1200, 1236, 1273, 1311, 1350] },
    { id: "e3", category: "occupancy_facility", lineItem: "Insurance", enabled: true, driverType: "annual_fixed", amounts: [12000, 12360, 12731, 13113, 13506] },
    { id: "e4", category: "occupancy_facility", lineItem: "Maintenance", enabled: true, driverType: "annual_fixed", amounts: [8000, 8240, 8487, 8742, 9004] },
    { id: "e5", category: "instructional_program", lineItem: "Curriculum", enabled: true, driverType: "per_student", amounts: [600, 618, 637, 656, 675] },
    { id: "e6", category: "technology", lineItem: "Technology", enabled: true, driverType: "per_student", amounts: [400, 412, 424, 437, 450] },
    { id: "e7", category: "administrative_general", lineItem: "Marketing", enabled: true, driverType: "annual_fixed", amounts: [15000, 15450, 15914, 16391, 16883] },
    { id: "e8", category: "administrative_general", lineItem: "Professional Development", enabled: true, driverType: "annual_fixed", amounts: [8000, 8240, 8487, 8742, 9004] },
    { id: "e9", category: "administrative_general", lineItem: "Accounting & Legal", enabled: true, driverType: "annual_fixed", amounts: [12000, 12360, 12731, 13113, 13506] },
  ],
  capitalAndDebtRows: [
    { id: "cd1", lineItem: "Facility Buildout Loan", enabled: true, driverType: "annual_fixed", amounts: [0, 0, 0, 0, 0], isLoan: true, loanPrincipal: 250000, loanRate: 6.5, loanTermYears: 10, purpose: "startup" },
    { id: "cd2", lineItem: "Furniture & Equipment", enabled: true, driverType: "annual_fixed", amounts: [25000, 10000, 10000, 5000, 5000], isLoan: false },
  ],
  priorYearSnapshot: { endingEnrollment: 85, totalRevenue: 1200000, totalExpenses: 1150000, endingCash: 75000 },
  openingBalances: { cash: 75000, accountsReceivable: 12000, fixedAssets: 180000, otherAssets: 5000, accountsPayable: 8000, currentDebtPortion: 20000, longTermDebt: 200000 },
  sourcesAndUses: {
    sources: [
      { lineItem: "Facility Buildout Loan", amount: 250000, category: "debt" },
      { lineItem: "Foundation Grant", amount: 50000, category: "grants" },
      { lineItem: "Operating Cash", amount: 75000, category: "cash" },
    ],
    uses: [
      { lineItem: "Facility Renovation", amount: 200000, category: "capital" },
      { lineItem: "Furniture & Equipment", amount: 50000, category: "capital" },
      { lineItem: "Working Capital Reserve", amount: 75000, category: "reserves" },
      { lineItem: "Pre-Opening Costs", amount: 50000, category: "startup" },
    ],
  },
  scenarios: [
    { name: "Base Case", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Low Enrollment", enrollmentAdjustment: -15, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "High Costs", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 10 },
  ],
  covenantThresholds: { minDSCR: 1.25, minDaysCashOnHand: 60, minMonthsRunway: 3, minCapacityUtil: 75 },
};

export const charterPublicFunding = {
  schoolProfile: {
    schoolName: "Civic Scholars Charter",
    state: "OH",
    schoolType: "charter_school",
    entityType: "nonprofit_501c3",
    ein: "31-5551234",
    schoolStage: "new_school",
    fundingProfile: "charter_public_funded",
    openingYear: 2026,
    currentStudents: 0,
    maxCapacity: 400,
    fiscalYearStartMonth: 7,
    isPartialFirstYear: true,
    year1OperatingMonths: 10,
    locationSecured: true,
    facilityStreet: "789 Elm Blvd",
    facilityCity: "Columbus",
    facilityState: "OH",
    facilityZip: "43215",
    ownershipType: "rent",
    monthlyRent: 18000,
    annualRentEscalation: 3,
    debtIncluded: true,
    lendingLabIntent: "plan_to_apply",
  },
  enrollment: { year1: 120, year2: 200, year3: 300, year4: 375, year5: 400 },
  revenue: {
    publicFundingPerStudent: 9500,
    annualTuitionIncrease: 2,
    annualFundraising: 30000,
    foundationGrants: 100000,
    capitalGifts: 50000,
  },
  revenueRows: [
    { id: "r1", category: "public_funding", lineItem: "State Per-Pupil Funding", enabled: true, driverType: "per_student", amounts: [9500, 9690, 9884, 10081, 10283], billingMonths: 12, paymentFrequency: "monthly", disbursementType: "direct" },
    { id: "r2", category: "public_funding", lineItem: "Federal Title I", enabled: true, driverType: "per_student", amounts: [800, 816, 832, 849, 866], billingMonths: 12, disbursementType: "reimbursement", reimbursementLagMonths: 2 },
    { id: "r3", category: "public_funding", lineItem: "Special Education Funding", enabled: true, driverType: "per_student", amounts: [1200, 1224, 1248, 1273, 1299], billingMonths: 12 },
    { id: "r4", category: "philanthropy", lineItem: "CSP Startup Grant", enabled: true, driverType: "annual_fixed", amounts: [100000, 75000, 50000, 0, 0], grantStatus: "confirmed" },
    { id: "r5", category: "philanthropy", lineItem: "Annual Fundraising", enabled: true, driverType: "annual_fixed", amounts: [30000, 40000, 50000, 60000, 70000] },
    { id: "r6", category: "other_revenue", lineItem: "Food Service Revenue", enabled: true, driverType: "per_student", amounts: [300, 309, 318, 328, 338] },
  ],
  staffingRows: [
    { id: "s1", roleName: "Executive Director", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 110000, benefitsEligible: true, benefitsRate: 28, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s2", roleName: "Principal", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 90000, benefitsEligible: true, benefitsRate: 28, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s3", roleName: "Dean of Students", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 72000, benefitsEligible: true, benefitsRate: 28, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s4", roleName: "Core Teachers", functionCategory: "instructional", employmentType: "full_time", fte: 6, annualizedRate: 52000, benefitsEligible: true, benefitsRate: 28, payrollTaxRate: 7.65, payrollLike: false, staffingMode: "ratio", studentRatio: 22, minFte: 4 },
    { id: "s5", roleName: "Special Education Teacher", functionCategory: "instructional", employmentType: "full_time", fte: 1, annualizedRate: 55000, benefitsEligible: true, benefitsRate: 28, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s6", roleName: "Instructional Aides", functionCategory: "instructional", employmentType: "full_time", fte: 3, annualizedRate: 30000, benefitsEligible: true, benefitsRate: 20, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s7", roleName: "Operations Manager", functionCategory: "operations", employmentType: "full_time", fte: 1, annualizedRate: 55000, benefitsEligible: true, benefitsRate: 28, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s8", roleName: "Office Staff", functionCategory: "administrative", employmentType: "full_time", fte: 2, annualizedRate: 38000, benefitsEligible: true, benefitsRate: 25, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s9", roleName: "School Counselor", functionCategory: "student_support", employmentType: "full_time", fte: 1, annualizedRate: 55000, benefitsEligible: true, benefitsRate: 28, payrollTaxRate: 7.65, payrollLike: false },
  ],
  expenseRows: [
    { id: "e1", category: "occupancy_facility", lineItem: "Facility Lease", enabled: true, driverType: "monthly", amounts: [18000, 18540, 19096, 19669, 20259], escalationRate: 3 },
    { id: "e2", category: "occupancy_facility", lineItem: "Utilities", enabled: true, driverType: "monthly", amounts: [2500, 2575, 2652, 2732, 2814] },
    { id: "e3", category: "occupancy_facility", lineItem: "Insurance", enabled: true, driverType: "annual_fixed", amounts: [18000, 18540, 19096, 19669, 20259] },
    { id: "e4", category: "occupancy_facility", lineItem: "Janitorial", enabled: true, driverType: "monthly", amounts: [1500, 1545, 1591, 1639, 1688] },
    { id: "e5", category: "instructional_program", lineItem: "Curriculum & Textbooks", enabled: true, driverType: "per_student", amounts: [700, 721, 743, 765, 788] },
    { id: "e6", category: "technology", lineItem: "Technology & Devices", enabled: true, driverType: "per_student", amounts: [500, 515, 530, 546, 562] },
    { id: "e7", category: "administrative_general", lineItem: "Marketing & Recruitment", enabled: true, driverType: "annual_fixed", amounts: [25000, 25750, 26523, 27318, 28138] },
    { id: "e8", category: "administrative_general", lineItem: "Professional Development", enabled: true, driverType: "annual_fixed", amounts: [15000, 15450, 15914, 16391, 16883] },
    { id: "e9", category: "administrative_general", lineItem: "Legal & Compliance", enabled: true, driverType: "annual_fixed", amounts: [20000, 20600, 21218, 21855, 22510] },
    { id: "e10", category: "administrative_general", lineItem: "Food Service", enabled: true, driverType: "per_student", amounts: [800, 824, 849, 874, 900] },
    { id: "e11", category: "administrative_general", lineItem: "Transportation", enabled: true, driverType: "per_student", amounts: [600, 618, 637, 656, 675] },
  ],
  capitalAndDebtRows: [
    { id: "cd1", lineItem: "Facility Improvement Loan", enabled: true, driverType: "annual_fixed", amounts: [0, 0, 0, 0, 0], isLoan: true, loanPrincipal: 500000, loanRate: 5.75, loanTermYears: 15, purpose: "startup" },
    { id: "cd2", lineItem: "FF&E Purchase", enabled: true, driverType: "annual_fixed", amounts: [75000, 25000, 30000, 15000, 10000], isLoan: false },
    { id: "cd3", lineItem: "Technology Infrastructure", enabled: true, driverType: "annual_fixed", amounts: [40000, 15000, 10000, 10000, 10000], isLoan: false },
  ],
  openingBalances: { cash: 50000, accountsReceivable: 0, fixedAssets: 0, otherAssets: 0, accountsPayable: 0, currentDebtPortion: 0, longTermDebt: 0 },
  sourcesAndUses: {
    sources: [
      { lineItem: "Facility Improvement Loan", amount: 500000, category: "debt" },
      { lineItem: "CSP Startup Grant", amount: 100000, category: "grants" },
      { lineItem: "Capital Campaign Gifts", amount: 50000, category: "equity" },
    ],
    uses: [
      { lineItem: "Facility Buildout", amount: 400000, category: "capital" },
      { lineItem: "FF&E", amount: 75000, category: "capital" },
      { lineItem: "Technology Setup", amount: 40000, category: "capital" },
      { lineItem: "Pre-Opening Staffing", amount: 60000, category: "startup" },
      { lineItem: "Working Capital", amount: 75000, category: "reserves" },
    ],
  },
  scenarios: [
    { name: "Base Case", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Slow Ramp", enrollmentAdjustment: -25, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Funding Cut", enrollmentAdjustment: 0, tuitionAdjustment: -5, expenseAdjustment: 0 },
    { name: "Cost Overrun", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 15 },
  ],
  covenantThresholds: { minDSCR: 1.15, minDaysCashOnHand: 45, minMonthsRunway: 2, minCapacityUtil: 70 },
};

export const charterADAGradeBand = {
  schoolProfile: {
    schoolName: "Heritage Academy Charter",
    state: "AZ",
    schoolType: "charter_school",
    entityType: "nonprofit_501c3",
    ein: "86-4441234",
    schoolStage: "new_school",
    fundingProfile: "charter_public_funded",
    openingYear: 2026,
    currentStudents: 0,
    maxCapacity: 600,
    fiscalYearStartMonth: 7,
    isPartialFirstYear: true,
    year1OperatingMonths: 10,
    locationSecured: true,
    facilityStreet: "1200 N Central Ave",
    facilityCity: "Phoenix",
    facilityState: "AZ",
    facilityZip: "85004",
    ownershipType: "rent",
    monthlyRent: 22000,
    annualRentEscalation: 3,
    debtIncluded: true,
    lendingLabIntent: "plan_to_apply",
    enrollmentRevenueMethod: "ada",
    charterDepositTiming: "monthly",
    priorYearADM: 0,
    priorYearADA: 0,
    gradeBandEnrollment: {
      k5: [80, 130, 180, 230, 260],
      m68: [40, 70, 100, 120, 140],
      h912: [0, 0, 20, 50, 100],
    },
    gradeBandPerPupil: { k5: 8200, m68: 9100, h912: 10500 },
  },
  enrollment: { year1: 120, year2: 200, year3: 300, year4: 400, year5: 500 },
  revenue: {},
  revenueRows: [
    { id: "state_local_perpupil", category: "public_funding", lineItem: "State Per-Pupil Funding", enabled: true, driverType: "per_student", amounts: [8500, 8670, 8843, 9020, 9200], billingMonths: 12 },
    { id: "r2", category: "public_funding", lineItem: "Federal Title I", enabled: true, driverType: "per_student", amounts: [750, 765, 780, 796, 812], billingMonths: 12 },
    { id: "r3", category: "public_funding", lineItem: "IDEA Special Ed", enabled: true, driverType: "per_student", amounts: [1100, 1122, 1144, 1167, 1191], billingMonths: 12 },
    { id: "r4", category: "philanthropy", lineItem: "CSP Startup Grant", enabled: true, driverType: "annual_fixed", amounts: [150000, 100000, 50000, 0, 0] },
    { id: "r5", category: "philanthropy", lineItem: "Annual Fundraising", enabled: true, driverType: "annual_fixed", amounts: [25000, 35000, 45000, 55000, 65000] },
    { id: "r6", category: "other_revenue", lineItem: "Before/After Care", enabled: true, driverType: "per_student", amounts: [400, 412, 424, 437, 450] },
  ],
  staffingRows: [
    { id: "s1", roleName: "Head of School", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 105000, benefitsEligible: true, benefitsRate: 26, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s2", roleName: "Assistant Principal", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 82000, benefitsEligible: true, benefitsRate: 26, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s3", roleName: "Lead Teachers", functionCategory: "instructional", employmentType: "full_time", fte: 5, annualizedRate: 50000, benefitsEligible: true, benefitsRate: 26, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s4", roleName: "SPED Teacher", functionCategory: "instructional", employmentType: "full_time", fte: 1, annualizedRate: 53000, benefitsEligible: true, benefitsRate: 26, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s5", roleName: "Instructional Aides", functionCategory: "instructional", employmentType: "full_time", fte: 3, annualizedRate: 28000, benefitsEligible: true, benefitsRate: 18, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s6", roleName: "Business Manager", functionCategory: "operations", employmentType: "full_time", fte: 1, annualizedRate: 62000, benefitsEligible: true, benefitsRate: 26, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s7", roleName: "Front Office", functionCategory: "administrative", employmentType: "full_time", fte: 2, annualizedRate: 36000, benefitsEligible: true, benefitsRate: 22, payrollTaxRate: 7.65, payrollLike: false },
  ],
  expenseRows: [
    { id: "e1", category: "occupancy_facility", lineItem: "Facility Lease", enabled: true, driverType: "monthly", amounts: [22000, 22660, 23340, 24040, 24761], escalationRate: 3 },
    { id: "e2", category: "occupancy_facility", lineItem: "Utilities", enabled: true, driverType: "monthly", amounts: [3000, 3090, 3183, 3278, 3377] },
    { id: "e3", category: "occupancy_facility", lineItem: "Property Insurance", enabled: true, driverType: "annual_fixed", amounts: [22000, 22660, 23340, 24040, 24761] },
    { id: "e4", category: "instructional_program", lineItem: "Curriculum", enabled: true, driverType: "per_student", amounts: [650, 670, 690, 710, 732] },
    { id: "e5", category: "technology", lineItem: "Devices & Software", enabled: true, driverType: "per_student", amounts: [450, 464, 478, 492, 507] },
    { id: "e6", category: "administrative_general", lineItem: "Marketing", enabled: true, driverType: "annual_fixed", amounts: [30000, 30900, 31827, 32782, 33765] },
    { id: "e7", category: "administrative_general", lineItem: "Professional Development", enabled: true, driverType: "annual_fixed", amounts: [12000, 12360, 12731, 13113, 13506] },
    { id: "e8", category: "administrative_general", lineItem: "Legal & Audit", enabled: true, driverType: "annual_fixed", amounts: [18000, 18540, 19096, 19669, 20259] },
    { id: "e9", category: "administrative_general", lineItem: "Food Service", enabled: true, driverType: "per_student", amounts: [750, 773, 796, 820, 845] },
  ],
  capitalAndDebtRows: [
    { id: "cd1", lineItem: "Startup Loan", enabled: true, driverType: "annual_fixed", amounts: [0, 0, 0, 0, 0], isLoan: true, loanPrincipal: 350000, loanRate: 6.0, loanTermYears: 10, purpose: "startup" },
    { id: "cd2", lineItem: "FF&E", enabled: true, driverType: "annual_fixed", amounts: [60000, 20000, 25000, 10000, 10000], isLoan: false },
  ],
  openingBalances: { cash: 75000, accountsReceivable: 0, fixedAssets: 0, otherAssets: 0, accountsPayable: 0, currentDebtPortion: 0, longTermDebt: 0 },
  sourcesAndUses: {
    sources: [
      { lineItem: "Startup Loan", amount: 350000, category: "debt" },
      { lineItem: "CSP Grant", amount: 150000, category: "grants" },
    ],
    uses: [
      { lineItem: "Facility Prep", amount: 250000, category: "capital" },
      { lineItem: "FF&E", amount: 60000, category: "capital" },
      { lineItem: "Pre-Opening Costs", amount: 50000, category: "startup" },
      { lineItem: "Working Capital Reserve", amount: 140000, category: "reserves" },
    ],
  },
  scenarios: [
    { name: "Base Case", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Low ADA", enrollmentAdjustment: -15, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Funding Cut", enrollmentAdjustment: 0, tuitionAdjustment: -8, expenseAdjustment: 0 },
  ],
  covenantThresholds: { minDSCR: 1.15, minDaysCashOnHand: 45, minMonthsRunway: 2, minCapacityUtil: 70 },
};

// Sample payload that exercises the Decision History sheet end-to-end. It
// reuses the microschoolStartup base and layers in customScenarios that cover
// every outcome (pursued/applied, pursued/pending, on_hold, declined) plus
// retrospective notes — so the Excel QA suite can verify the "Decision
// History" sheet's contents (headers, row order, color coding, applied tag,
// retrospective copy) end-to-end in lender + underwriting workbooks.
export const microschoolWithDecisions = {
  ...microschoolStartup,
  customScenarios: [
    {
      // Pursued + already folded into the base model. Should sort first
      // (pursued group, most recent outcomeUpdatedAt).
      name: "Add Middle School program",
      decisionType: "add_program",
      outcomeStatus: "pursued",
      createdAt: "2025-02-01T10:00:00Z",
      outcomeUpdatedAt: "2025-04-10T10:00:00Z",
      appliedToModelAt: "2025-04-12T09:00:00Z",
      retrospective: "Launched in fall 2025; enrollment hit plan within 1 student.",
      overrides: {
        addProgramName: "Middle School",
        addProgramGradeBand: "6-8",
        addProgramTuition: 14000,
        addProgramEnrollment: [8, 12, 16, 18, 18],
        addProgramAddedFte: 2,
      },
    },
    {
      // Pursued but not yet applied — should render the [PENDING] tag.
      // Older outcomeUpdatedAt → sorts after the applied pursued item.
      name: "Increase retention focus",
      decisionType: "change_enrollment",
      outcomeStatus: "pursued",
      createdAt: "2025-01-15T10:00:00Z",
      outcomeUpdatedAt: "2025-03-05T10:00:00Z",
      retrospective: "Retention initiatives approved; planner will reflect after Q2 board review.",
      overrides: {
        retentionRate: 92,
        enrollmentDelta: [2, 3, 3, 3, 3],
      },
    },
    {
      // On hold — should sort after pursued, before declined.
      name: "Evaluate downtown campus",
      decisionType: "evaluate_site",
      outcomeStatus: "on_hold",
      createdAt: "2025-02-20T10:00:00Z",
      outcomeUpdatedAt: "2025-03-25T10:00:00Z",
      retrospective: "Landlord negotiations paused while waiting on city zoning ruling.",
      overrides: {
        monthlyRent: 8500,
        rentEscalation: 4,
        sqftDelta: 1500,
        siteFitOutCost: 75000,
      },
    },
    {
      // Declined — most recent in declined group → sorts first within group.
      name: "Reduce K cohort",
      decisionType: "change_enrollment",
      outcomeStatus: "declined",
      createdAt: "2025-01-10T10:00:00Z",
      outcomeUpdatedAt: "2025-03-15T10:00:00Z",
      retrospective: "Board declined; enrollment goals retained as originally modeled.",
      overrides: {
        enrollmentDelta: [-5, -3, 0, 0, 0],
        tuitionDeltaPerStudent: -500,
      },
    },
    {
      // Declined with older outcomeUpdatedAt → sorts last within declined.
      name: "Move to larger building",
      decisionType: "evaluate_site",
      outcomeStatus: "declined",
      createdAt: "2024-12-01T10:00:00Z",
      outcomeUpdatedAt: "2025-02-10T10:00:00Z",
      retrospective: "Costs out of reach; revisited next year after capital campaign.",
      overrides: {
        monthlyRent: 12000,
        sqftDelta: 4000,
      },
    },
  ],
};

// Task #454 — Tutoring center (AZ, fee-per-session storefront with a small
// ESA mix). Promoted from a microschool piggyback to a first-class persona
// so the consultant + export pipelines have a representative shape that
// actually reflects the contract-staff + per-student-fee + small-storefront
// economics rather than inheriting microschool defaults. Mirrors
// `tutoringCenterFixture` in lib/finance/src/test-fixtures.ts (the latter
// is the cross-engine golden-snapshot fixture; this is the full-shape
// payload the wizard / preflight / export pipeline sees).
export const tutoringCenterFee = {
  schoolProfile: {
    schoolName: "Saguaro Tutoring Center",
    state: "AZ",
    schoolType: "tutoring_center",
    entityType: "llc_single",
    ein: "86-7770001",
    schoolStage: "new_school",
    fundingProfile: "hybrid_mixed",
    openingYear: 2026,
    currentStudents: 0,
    maxCapacity: 60,
    fiscalYearStartMonth: 7,
    isPartialFirstYear: true,
    year1OperatingMonths: 10,
    locationSecured: true,
    facilityStreet: "1500 W Indian School Rd",
    facilityCity: "Phoenix",
    facilityState: "AZ",
    facilityZip: "85015",
    ownershipType: "rent",
    monthlyRent: 2200,
    annualRentEscalation: 3,
    debtIncluded: false,
    enrollmentGrowthRate: 20,
    stateFundingMethodology: "other",
  },
  enrollment: { year1: 20, year2: 35, year3: 45, year4: 55, year5: 60 },
  revenue: {
    tuitionPerStudent: 3500,
    annualTuitionIncrease: 3,
    annualFundraising: 3000,
    annualDonations: 0,
  },
  revenueRows: [
    { id: "r1", category: "tuition_and_fees", lineItem: "Annual Tutoring Fee", enabled: true, driverType: "per_student", amounts: [3500, 3605, 3713, 3825, 3939], billingMonths: 10 },
    { id: "r2", category: "tuition_and_fees", lineItem: "Materials & Assessment Fee", enabled: true, driverType: "per_student", amounts: [200, 200, 200, 200, 200], billingMonths: 12, escalationRate: 0, escalationRateOverridden: true },
    { id: "esa_revenue", category: "school_choice", lineItem: "AZ ESA Funds (partial mix)", enabled: true, driverType: "per_student", amounts: [2500, 2575, 2652, 2732, 2814], billingMonths: 12 },
    { id: "refundable_tax_credit", category: "school_choice", lineItem: "Refundable Tax Credit", enabled: false, driverType: "per_student", amounts: [0, 0, 0, 0, 0], billingMonths: 12 },
    { id: "r4", category: "philanthropy", lineItem: "Community Sponsorships", enabled: true, driverType: "annual_fixed", amounts: [3000, 4000, 5000, 6000, 7000] },
  ],
  staffingRows: [
    { id: "s1", roleName: "Center Director", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 58000, benefitsEligible: true, benefitsRate: 18, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s2", roleName: "Lead Tutor", functionCategory: "instructional", employmentType: "full_time", fte: 1, annualizedRate: 42000, benefitsEligible: true, benefitsRate: 18, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s3", roleName: "Contract Tutors", functionCategory: "instructional", employmentType: "contract", fte: 2, annualizedRate: 30000, benefitsEligible: false, benefitsRate: 0, payrollTaxRate: 0, payrollLike: false, staffingMode: "ratio", studentRatio: 10, minFte: 2, maxFte: 6 },
    { id: "s4", roleName: "Front Desk / Scheduler", functionCategory: "administrative", employmentType: "part_time", fte: 0.5, annualizedRate: 28000, benefitsEligible: false, benefitsRate: 0, payrollTaxRate: 7.65, payrollLike: false },
  ],
  facilities: {
    monthlyRent: 2200,
    annualRentIncrease: 3,
    annualUtilities: 2640,
    annualInsurance: 1800,
    curriculumCostPerStudent: 180,
    techCostPerStudent: 120,
    annualMarketing: 6000,
    annualSalaryIncrease: 3,
    generalCostInflation: 2.5,
  },
  expenseRows: [
    { id: "e1", category: "occupancy_facility", lineItem: "Storefront Lease", enabled: true, driverType: "monthly", amounts: [2200, 2266, 2334, 2404, 2476], escalationRate: 3 },
    { id: "e2", category: "occupancy_facility", lineItem: "Utilities", enabled: true, driverType: "monthly", amounts: [220, 226, 232, 238, 245] },
    { id: "e3", category: "occupancy_facility", lineItem: "Insurance", enabled: true, driverType: "annual_fixed", amounts: [1800, 1845, 1891, 1938, 1987] },
    { id: "e4", category: "instructional_program", lineItem: "Curriculum & Assessments", enabled: true, driverType: "per_student", amounts: [180, 185, 190, 196, 202] },
    { id: "e5", category: "technology", lineItem: "Scheduling & Tutoring Software", enabled: true, driverType: "per_student", amounts: [120, 124, 128, 132, 136] },
    { id: "e6", category: "administrative_general", lineItem: "Marketing & Local Ads", enabled: true, driverType: "annual_fixed", amounts: [6000, 6150, 6304, 6461, 6623] },
    { id: "e7", category: "administrative_general", lineItem: "Bookkeeping & Compliance", enabled: true, driverType: "annual_fixed", amounts: [3600, 3690, 3782, 3877, 3974] },
  ],
  capitalAndDebtRows: [],
  openingBalances: { cash: 12000, accountsReceivable: 0, fixedAssets: 3000, otherAssets: 0, accountsPayable: 0, currentDebtPortion: 0, longTermDebt: 0 },
  sourcesAndUses: {
    sources: [{ lineItem: "Owner Savings", amount: 15000, category: "equity" }],
    uses: [{ lineItem: "Startup Costs", amount: 12000, category: "startup" }, { lineItem: "Working Capital Reserve", amount: 3000, category: "reserves" }],
  },
  scenarios: [
    { name: "Base Case", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Slow Ramp", enrollmentAdjustment: -25, tuitionAdjustment: 0, expenseAdjustment: 0 },
  ],
  covenantThresholds: { minDSCR: 1.0, minDaysCashOnHand: 30, minMonthsRunway: 2 },
};

// Task #454 — Learning pod (AZ, ESA-eligible premium small cohort).
// Promoted from a microschool piggyback to a first-class persona so the
// pod's distinctive economics (small capacity, single-facilitator staffing,
// ESA + premium tuition) are exercised by the consultant + export pipelines
// rather than inheriting microschool defaults. Mirrors `learningPodFixture`
// in lib/finance/src/test-fixtures.ts.
export const learningPodHybrid = {
  schoolProfile: {
    schoolName: "Sonoran Learning Pod",
    state: "AZ",
    schoolType: "learning_pod",
    entityType: "llc_single",
    ein: "86-7770002",
    schoolStage: "new_school",
    fundingProfile: "hybrid_mixed",
    openingYear: 2026,
    currentStudents: 0,
    maxCapacity: 15,
    fiscalYearStartMonth: 7,
    isPartialFirstYear: true,
    year1OperatingMonths: 10,
    locationSecured: true,
    facilityStreet: "4520 N 7th Ave",
    facilityCity: "Phoenix",
    facilityState: "AZ",
    facilityZip: "85013",
    ownershipType: "rent",
    monthlyRent: 1200,
    annualRentEscalation: 3,
    debtIncluded: false,
    enrollmentGrowthRate: 15,
    stateFundingMethodology: "other",
  },
  enrollment: { year1: 8, year2: 10, year3: 12, year4: 14, year5: 15 },
  revenue: {
    tuitionPerStudent: 10000,
    annualTuitionIncrease: 3,
    annualFundraising: 2000,
    annualDonations: 0,
  },
  revenueRows: [
    { id: "r1", category: "tuition_and_fees", lineItem: "Pod Tuition", enabled: true, driverType: "per_student", amounts: [10000, 10300, 10609, 10927, 11255], billingMonths: 10 },
    { id: "r2", category: "tuition_and_fees", lineItem: "Enrichment Fee", enabled: true, driverType: "per_student", amounts: [400, 400, 400, 400, 400], billingMonths: 12, escalationRate: 0, escalationRateOverridden: true },
    { id: "esa_revenue", category: "school_choice", lineItem: "AZ ESA Funds", enabled: true, driverType: "per_student", amounts: [7000, 7210, 7426, 7649, 7878], billingMonths: 12 },
    { id: "refundable_tax_credit", category: "school_choice", lineItem: "Refundable Tax Credit", enabled: false, driverType: "per_student", amounts: [0, 0, 0, 0, 0], billingMonths: 12 },
    { id: "r4", category: "philanthropy", lineItem: "Family Fundraising", enabled: true, driverType: "annual_fixed", amounts: [2000, 2500, 3000, 3500, 4000] },
    { id: "r5", category: "tuition_offsets", lineItem: "Sibling Discount", enabled: true, driverType: "percent_of_base", amounts: [10, 10, 10, 10, 10], percentBase: "r1" },
  ],
  staffingRows: [
    { id: "s1", roleName: "Lead Facilitator", functionCategory: "school_leadership", employmentType: "full_time", fte: 1, annualizedRate: 50000, benefitsEligible: true, benefitsRate: 18, payrollTaxRate: 7.65, payrollLike: false },
    { id: "s2", roleName: "Enrichment Specialist", functionCategory: "instructional", employmentType: "part_time", fte: 0.4, annualizedRate: 35000, benefitsEligible: false, benefitsRate: 0, payrollTaxRate: 7.65, payrollLike: false },
  ],
  facilities: {
    monthlyRent: 1200,
    annualRentIncrease: 3,
    annualUtilities: 2160,
    annualInsurance: 1500,
    curriculumCostPerStudent: 600,
    techCostPerStudent: 350,
    annualMarketing: 1500,
    annualSalaryIncrease: 3,
    generalCostInflation: 2.5,
  },
  expenseRows: [
    { id: "e1", category: "occupancy_facility", lineItem: "Shared Space Rent", enabled: true, driverType: "monthly", amounts: [1200, 1236, 1273, 1311, 1351], escalationRate: 3 },
    { id: "e2", category: "occupancy_facility", lineItem: "Utilities & Internet", enabled: true, driverType: "monthly", amounts: [180, 185, 190, 196, 202] },
    { id: "e3", category: "occupancy_facility", lineItem: "Insurance", enabled: true, driverType: "annual_fixed", amounts: [1500, 1538, 1576, 1615, 1656] },
    { id: "e4", category: "instructional_program", lineItem: "Curriculum & Materials", enabled: true, driverType: "per_student", amounts: [600, 618, 637, 656, 675] },
    { id: "e5", category: "technology", lineItem: "Devices & Software", enabled: true, driverType: "per_student", amounts: [350, 361, 372, 383, 394] },
    { id: "e6", category: "administrative_general", lineItem: "Marketing", enabled: true, driverType: "annual_fixed", amounts: [1500, 1545, 1591, 1639, 1688] },
    { id: "e7", category: "administrative_general", lineItem: "Bookkeeping & Compliance", enabled: true, driverType: "annual_fixed", amounts: [2400, 2460, 2522, 2585, 2650] },
  ],
  capitalAndDebtRows: [],
  openingBalances: { cash: 8000, accountsReceivable: 0, fixedAssets: 1500, otherAssets: 0, accountsPayable: 0, currentDebtPortion: 0, longTermDebt: 0 },
  sourcesAndUses: {
    sources: [{ lineItem: "Founder Savings", amount: 10000, category: "equity" }],
    uses: [{ lineItem: "Startup Costs", amount: 8000, category: "startup" }, { lineItem: "Working Capital Reserve", amount: 2000, category: "reserves" }],
  },
  scenarios: [
    { name: "Base Case", enrollmentAdjustment: 0, tuitionAdjustment: 0, expenseAdjustment: 0 },
    { name: "Low ESA Utilization", enrollmentAdjustment: 0, tuitionAdjustment: -10, expenseAdjustment: 0 },
  ],
  covenantThresholds: { minDSCR: 1.0, minDaysCashOnHand: 30, minMonthsRunway: 2 },
};
