import {
  charterPublicFunding,
  homeschoolCoopMixed,
  learningPodHybrid,
  privateSchoolWithESA,
  tutoringCenterFee,
} from "../../../api-server/tests/sample-payloads";
import { autoResolveBlockingFlags } from "./auto-resolve-flags";
import { seedPersona } from "./seed-persona";
import type { APIRequestContext, Page } from "./test";
import { expect } from "./test";

// Shared persona seeding + auth-prime helpers for the export-download
// e2e specs (`export-download-personas.spec.ts` from Task #449 and
// `export-download-extra-personas.spec.ts` from Task #450). Task #451
// replaced the hand-coded per-persona `flagResolutions` arrays with
// `autoResolveBlockingFlags`, which runs the same consultant-engine
// detector the server runs and seeds a reason for every blocking flag —
// so adding a persona below now needs only the data fixture.

const TEST_PASSWORD = "PlaywrightTest12345!";

export interface SeededFixture {
  token: string;
  modelId: number;
  email: string;
}

export interface PersonaCase {
  label: string;
  modelName: string;
  data: Record<string, unknown>;
}

export const PERSONAS: PersonaCase[] = [
  {
    label: "charter-public-funded",
    modelName: "Civic Scholars Charter (E2E)",
    data: charterPublicFunding as unknown as Record<string, unknown>,
  },
  {
    label: "private-high-school",
    modelName: "Heritage Academy (E2E)",
    data: privateSchoolWithESA as unknown as Record<string, unknown>,
  },
  {
    label: "homeschool-coop",
    modelName: "Liberty Learning Co-Op (E2E)",
    data: homeschoolCoopMixed as unknown as Record<string, unknown>,
  },
  // Task #454 — first-class tutoring-center + learning-pod personas. These
  // are no longer microschool piggybacks: they have distinct facility +
  // staffing benchmarks and carry their own cross-engine goldens (see
  // `tutoringCenterGolden` / `learningPodGolden` in cross-engine-test.ts).
  // Adding them here exercises the export pipeline against the new
  // school-type defaults end-to-end.
  {
    label: "tutoring-center",
    modelName: "Saguaro Tutoring Center (E2E)",
    data: tutoringCenterFee as unknown as Record<string, unknown>,
  },
  {
    label: "learning-pod",
    modelName: "Sonoran Learning Pod (E2E)",
    data: learningPodHybrid as unknown as Record<string, unknown>,
  },
];

export async function seedPersonaModel(
  request: APIRequestContext,
  persona: PersonaCase,
): Promise<SeededFixture> {
  const stamp = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `playwright-${persona.label}-${stamp}@e2e.schoolstack.test`;

  const registerRes = await request.post("/api/auth/register", {
    data: {
      email,
      password: TEST_PASSWORD,
      name: "Playwright Founder",
    },
  });
  expect(
    registerRes.ok(),
    `register failed: ${registerRes.status()} ${await registerRes.text()}`,
  ).toBeTruthy();
  const { token } = (await registerRes.json()) as { token: string };
  await seedPersona(request, token);

  const authHeaders = { Authorization: `Bearer ${token}` };

  // currentStep: 12 lands the wizard on the Export step on first render so
  // the ExportCards are immediately interactable. The full persona payload
  // is sent in the create POST (rather than create + PUT) because the
  // export pipeline only reads what's been persisted; doing it in one round
  // trip keeps the spec fast for three personas in a row.
  //
  // assumptionFlagResponses is folded into the same `data` payload so the
  // export routes find the resolutions when checkUnresolvedFlags runs —
  // otherwise the lender + board JSON endpoints 422 with "Export blocked".
  // Task #451: the resolutions are auto-generated by running the same
  // assumption-flag detector the consultant engine uses, so adding or
  // renaming a warning rule no longer breaks this spec.
  const flagResolutions = await autoResolveBlockingFlags(persona.data);
  const dataWithFlagResponses: Record<string, unknown> = {
    ...persona.data,
    assumptionFlagResponses: flagResolutions,
  };
  const createRes = await request.post("/api/models", {
    headers: authHeaders,
    data: {
      name: persona.modelName,
      currentStep: 12,
      data: dataWithFlagResponses,
    },
  });
  expect(
    createRes.ok(),
    `create model (${persona.label}) failed: ${createRes.status()} ${await createRes.text()}`,
  ).toBeTruthy();
  const { id: modelId } = (await createRes.json()) as { id: number };

  // Preflight: hit the consultant endpoint and confirm zero unresolved
  // warning/critical flags BEFORE we drive the browser. If a future
  // engine change adds a new blocking flag for this persona, this
  // assertion fails with a clear "blocking flag detected" diagnostic
  // pointing at the exact field — much better than the opaque
  // "Failed to load packet" modal error the user would otherwise hit.
  const consultantRes = await request.get(
    `/api/models/${modelId}/consultant`,
    { headers: authHeaders },
  );
  expect(
    consultantRes.ok(),
    `consultant fetch (${persona.label}) failed: ${consultantRes.status()} ${await consultantRes.text()}`,
  ).toBeTruthy();
  const consultantBody = (await consultantRes.json()) as {
    assumptionFlags?: Array<{
      severity: string;
      flagType: string;
      field: string;
      reason?: string;
    }>;
  };
  const blockingFlags = (consultantBody.assumptionFlags ?? []).filter(
    (f) =>
      (f.severity === "warning" || f.severity === "critical") &&
      !(f.reason ?? "").trim(),
  );
  expect(
    blockingFlags,
    `Persona ${persona.label} has unresolved blocking flag(s): ${blockingFlags
      .map((f) => `${f.flagType}:${f.field}`)
      .join(", ")}. autoResolveBlockingFlags should have explained these — check that the consultant engine and the helper agree on flagType/field shapes for this persona.`,
  ).toEqual([]);

  return { token, modelId, email };
}

export async function primeAuthToken(page: Page, token: string): Promise<void> {
  // Inject the JWT before any app code runs so AuthProvider sees it on
  // first render. Equivalent to logging in through the UI, minus the form.
  await page.addInitScript((value) => {
    window.localStorage.setItem("auth_token", value);
  }, token);
}
